openstates/people

scripts/lint_yaml.py, scripts/tests/test_lint.py, settings.yml
=> add vacancy validation

data/vt/people/Dick-Mazza-1acec5ba-9c21-4166-9307-d6958608fb41.yml, scripts/lint_yaml.py, scripts/tests/test_to_database.py, scripts/to_database.py, scripts/utils.py, settings.yml
add posts and import them, openstates/openstates#2708
=> Import posts

data/nj/people/Kristin-M-Corrado-0880a4b0-8e91-484b-aa12-6e0444838c44.yml, data/nj/people/Verlina-Reynolds-Jackson-b432ec8c-f914-47dc-addd-740dfc95daaf.yml
No changes to committees, in the special elections the incumbents were elected. As a result, there are only two minor changes: one to an image, and one to a district office.
Part of #38.
=> Update New Jersey for 2019

scripts/to_database.py
This gives a pretty significant speedup which should help with the performance of to_database.py. #56.
=> Use yaml.CLoader when loading YAML files

data/ut/people/Andrew-Stoddard-eac36970-1c63-4b4c-81b1-3a39536bd69d.yml, data/ut/people/Brad-R-Wilson-7203ffd4-b488-486d-b81c-8437cc50fc88.yml, data/ut/people/Brady-Brammer-b8751ce0-ba9b-44a0-8658-9cc9dc5f4c2c.yml, data/ut/people/Calvin-R-Musselman-036ab735-ad82-450e-a5ca-098b1436cb90.yml, data/ut/people/Dan-N-Johnson-93cbbcce-172d-4857-b12d-3ea97f10ef66.yml, data/ut/people/Daniel-McCay-6540aa74-9456-4b29-9b56-cadd31104db2.yml, data/ut/people/David-G-Buxton-f30c3419-d198-4c97-89ed-271e469ba883.yml, data/ut/people/Derek-Kitchen-8b1630fd-d86e-4c72-a6be-584d65bb8de0.yml, data/ut/people/Jeffrey-D-Stenquist-58a35084-a6c6-421a-81d9-91d9c3dc6d5f.yml, data/ut/people/Jen-Dailey-Provost-b32f9174-73af-4db3-877b-1c368bd4e62e.yml, data/ut/people/Joel-Ferry-627d55e0-5965-41f3-a5c7-94b3abac551c.yml, data/ut/people/Jon-Hawkins-e214e4ef-2df9-41a2-9113-98715f5a791c.yml, data/ut/people/Kathleen-Riebe-67c6161b-0222-4702-85ce-7409bc5bc86a.yml, data/ut/people/Kirk-A-Cullimore-c421a26f-c1c1-4398-be94-d77d312ea3fe.yml, data/ut/people/Lawanna-Lou-Shurtliff-b4be5b77-1d99-4c17-a387-6dab33eb56ed.yml, data/ut/people/Mark-A-Strong-5d383c2b-0450-48db-92bf-e20977953cd8.yml, data/ut/people/Melissa-Garff-Ballard-861428f5-6456-4c94-b1ed-838b01a7d845.yml, data/ut/people/Phil-Lyman-e3cfd26d-2088-4bed-b4e6-0bc77b436ef9.yml, data/ut/people/Rex-P-Shipp-66ec0903-117f-4006-8e05-e7326330fc63.yml, data/ut/people/Ronald-Winterton-5079192a-3d15-4a00-b0c7-2cf29d320035.yml, data/ut/people/Stephanie-Pitcher-edf0f18c-4b89-4d34-a2eb-6ce79accdaa7.yml, data/ut/people/Steve-Waldrip-b2ff2155-53b1-421f-9499-8924a7f330d5.yml, data/ut/people/Suzanne-Harrison-5e276370-80fe-4ace-81e0-414b26fa551c.yml
Some Utah legislators have had changes to their contact info and/or links. Update the YAML with these changes.
=> Update contact info and links for Utah legislators

data/ny/people/Judy-Griffin-0084a20e-9727-44d0-a60e-f074d17e65ef.yml
=> Fix Judy Griffin Party

data/id/organizations/Agricultural-Affairs-b030086a-f5d8-4615-a7d1-61948f10bff7.yml, data/id/organizations/Economic-Outlook-and-Revenue-Assessment-Committee-f6ea7071-e270-42c4-a1b9-1f1e7a6532e2.yml, data/id/organizations/Joint-Legislative-Oversight-Committee-bdba06af-b7eb-4d54-bef8-ac2f43bd7dbe.yml, data/id/organizations/Local-Government-and-Taxation-86159ac2-9006-4d8f-b0c6-d16a6c612db2.yml, data/id/organizations/Resources-and-Environment-d93ceb21-638b-4644-b1b6-c08b388c87fe.yml, data/id/people/Regina-M-Bayer-ba070f7d-f6c5-4c52-a62f-a58fedac7ed5.yml, data/id/retired/Clifford-R-Bayer-a2b5511c-3af9-4293-8353-7afca5d1d47d.yml
Clifford Bayer Became the chief of staff of U.S. Congressman Russ Fulcher (Republican, Idaho). Regina Bayer was appointed by Gov. Brad Little (R) to replace Clifford on January 25, 2019.
=> ID: Retirement + Appointment

data/ms/retired/Tyrone-Ellis-3ab60f85-a50d-42c8-a98d-b979d792986d.yml
Source news report confirmed actual retirement date of Friday June 30 2017. This was causing fun date parsing errors :)
=> Illegal Date 2017-06-31 to 2017-06-30

scripts/retire.py
https://github.com/openstates/people/issues/196
=> Adding Date Validation for END_DATE

data/pa/organizations/Banking--Insurance-36fab1db-43ea-4f8b-a69b-46b96016276a.yml, data/pa/organizations/Communications--Technology-2a495973-d690-467b-956c-bb3e7a571549.yml, data/pa/organizations/Community-Economic--Recreational-Development-cdb5ded8-3838-480f-bd1a-4b12fae24146.yml, data/pa/organizations/Education-cbe5703b-2171-43f8-8ab4-43f7d84b2e98.yml, data/pa/organizations/Environmental-Resources--Energy-040aec11-b7cc-49e1-a0f0-aada03aea41c.yml, data/pa/organizations/Intergovernmental-Operations-a4f4d580-9d52-4ec8-8735-407f09d1b811.yml, data/pa/organizations/Judiciary-0ddbbf76-e95c-4181-b1e4-7471b08010a1.yml, data/pa/organizations/Labor--Industry-b261a827-9c07-48c7-b0f6-2e72e0aaf736.yml, data/pa/organizations/Law--Justice-3d70dbdd-d4a8-4ef5-801e-f30896635dce.yml, data/pa/organizations/Rules--Executive-Nominations-7687884d-73f6-482c-b041-8a41a779e4cc.yml, data/pa/organizations/State-Government-bdeaf6d7-f7d8-4920-8930-6d89431591d6.yml, data/pa/people/Doug-Mastriano-cda65f80-13e8-463c-88fa-6f5569a599bf.yml, data/pa/people/Joe-Pittman-722f324f-db47-4ce2-9cbc-93f29ae38158.yml, data/pa/people/Pam-Iovino-836d57fc-a5ea-4218-9599-1ddb148da3ec.yml, data/pa/retired/Donald-C-White-b22468c0-44dc-4c36-bfd3-723ed2e9df3c.yml, data/pa/retired/Guy-Reschenthaler-a73761e3-9242-4809-a9b9-aeb5c728cb52.yml, data/pa/retired/Mike-Folmer-377312a5-dead-4434-b19e-f9b392fb64fa.yml, data/pa/retired/Richard-L-Alloway-cddcc672-bcab-4907-a017-35e5a52bc09f.yml, settings.yml
Updated several PA Senators that were outdated. #190
=> Update pa senators

data/pa/people/Malcolm-Kenyatta-96711736-a47d-4bd6-bcc3-92297ec01516.yml
Based on information here: https://www.legis.state.pa.us/cfdocs/legis/home/member_information/House_bio.cfm?id=1860
=> Updated Kenyatta's phones

scripts/merge.py, scripts/tests/test_merge.py
made interactive merge tool a lot smarter
=> improvements to merge tool

data/id/organizations/Agricultural-Affairs-51a6d5aa-ff2d-4329-b1a4-d45663fb2ff9.yml, data/id/organizations/Judiciary-Rules-and-Administration-a7620bfa-4076-4876-97ef-e100b9760af7.yml, data/id/organizations/Revenue-and-Taxation-8325f196-5b9e-4707-a337-c0bd8b30d7a2.yml, data/id/people/Lauren-Necochea-f2af3ae4-9051-488f-be6d-d87bcc832859.yml, data/id/people/Megan-Kiska-72d5f99c-803b-4564-84ca-e943c081d2d6.yml, data/id/retired/Mathew-W-Mat-Erpelding-1903ff33-9ae0-4c0f-98b5-84a9e79cdcec.yml, data/id/retired/Thomas-Dayley-c4a6ad64-07ce-468f-8ac6-16123348be18.yml
Retired: https://ballotpedia.org/Mathew_Erpelding
Appointed: https://ballotpedia.org/Lauren_Necochea
=> ID: retire mathew erpelding, appoint lauren necochea

data/va/people/Ghazala-F-Hashmi-2ae6c10e-e6d0-4033-927f-0b067b2ba0fc.yml, data/va/people/Jennifer-A-Kiggans-0aea6a95-df57-407e-a70d-b809a24401a2.yml, data/va/people/John-J-Bell-0f319f26-2e53-45e0-a349-411d09634b5e.yml, data/va/people/Joseph-D-Morrissey-1710258b-5ff4-4ee9-873b-7f2e43ca5ce9.yml
Thank you for you work on this project! Our friends in Virginia are working on a time sensitive campaign so if there is anyway this data could be merged soon that would be great.
Let me know if there are any adjustments need to the patch.
jamie
=> adding four missing email addresses to virginia senators.

data/id/people/Tim-Remington-c07e2d6e-5789-4265-b068-9a189fcc062b.yml, data/id/retired/John-Green-34f39bdf-c11d-45e5-9c09-f1c4617429bc.yml
https://ballotpedia.org/John_Green_(Idaho)
https://ballotpedia.org/Tim_Remington
=> ID: tim remington replaces john green

scripts/to_database.py, scripts/unmatched_legislators.py, scripts/utils.py
=> Unmatched names

scripts/unmatched_legislators.py
=> add command to go back and retroactively match historical records

README.md, poetry.lock, pyproject.toml, scripts/tests/django_test_settings.py, scripts/tests/test_to_database.py, scripts/to_database.py, scripts/to_yaml.py, scripts/unmatched_legislators.py, scripts/utils.py
=> switch to openstates-core

scripts/to_csv.py
bucket was set incorrectly, fix for #276
=> fix bucket and print upload status

data/nc/organizations/Appropriations-on-Health-and-Human-Services-cefe8dee-4bfa-4411-9055-440a69a7c3f5.yml, data/nc/organizations/Commerce-and-Insurance-1a19ae47-0874-4672-89de-7c6c782e88b4.yml, data/nc/organizations/Elections-Senate-Select-Committee-on-97e9a2f1-5fd5-4605-bcfb-4334dd6c012a.yml, data/nc/organizations/Finance-db4c34f9-da3e-4a51-8e2d-f9cbedfeb547.yml, data/nc/organizations/Health-Care-12a9ac10-22fe-411b-a2b8-490d7e584b85.yml, data/nc/organizations/Judicial-Reform-and-Redistricting-Senate-Select-Committee-on-429685aa-cc4b-477d-a1f3-ed9343935947.yml, data/nc/organizations/Judiciary-6219114f-0b01-4def-96ec-d4a1440a8692.yml, data/nc/organizations/Nominations-Senate-Select-Committee-on-c7aed5a7-bb47-4dcb-8a49-f31bf315978a.yml, data/nc/organizations/North-Carolina-River-Water-Quality-Senate-Select-Committee-on-1ac6fa02-e3b8-4889-994c-e8b1e1ec7b13.yml, data/nc/organizations/Pensions-and-Retirement-and-Aging-fa2f14a9-f280-4b15-bedf-e1fca1715f09.yml, data/nc/organizations/Redistricting-2633d000-bf96-44ca-bae7-477f42c30c35.yml, data/nc/organizations/Rules-and-Operations-of-the-Senate-a2813011-34a2-463e-867c-a3704771c569.yml, data/nc/people/Henry-Michaux-4fc71d5b-52cf-4df7-959c-44d0471f9964.yml, data/nc/people/Jake-Johnson-11c5404c-5cb6-4f99-84a5-711a23e6295f.yml, data/nc/people/Jeffrey-McNeely-09d4ccb5-4456-4f33-aea7-36f3e2ef9e43.yml, data/nc/people/Jim-Perry-111c38fc-67e4-4dfb-9d3b-3fe33fb3c8aa.yml, data/nc/people/Kristin-Baker-9f6b2b82-9747-4a89-9c58-b6580e9ca378.yml, data/nc/people/Perrin-Jones-215606a5-f44f-4e03-8617-b122900b978b.yml, data/nc/people/Rob-Bryan-26f3582f-e49c-4639-8d5b-86867de1f02c.yml, data/nc/people/Scott-Brewer-840b46bf-b314-4192-84a0-f641b13d4306.yml, data/nc/retired/Cody-Henson-181b27fd-2267-4d29-87a8-2cea848bde01.yml, data/nc/retired/Dan-Bishop-aeda3016-da15-448e-9ae4-62da790b3129.yml, data/nc/retired/Floyd-B-McKissick-Jr-74b59014-cfdc-44ef-a6e7-c9ab4c4ffbb3.yml, data/nc/retired/Gregory-F-Murphy-MD-cd20df05-7f56-40c0-b093-ff967fd34b4c.yml, data/nc/retired/Ken-Goodman-4dca2d65-7b85-4c5b-832c-6098c3b0cace.yml, data/nc/retired/Linda-P-Johnson-95242316-31a6-4e6c-9898-ffebd3033c5c.yml, data/nc/retired/Rena-W-Turner-578600d4-e249-425b-a7cd-df3296c1e224.yml, settings.yml
working on a merged branch of #281
=> NC with retirements

data/nc/people/Henry-Michaux-4fc71d5b-52cf-4df7-959c-44d0471f9964.yml, data/nc/people/Jake-Johnson-11c5404c-5cb6-4f99-84a5-711a23e6295f.yml, data/nc/people/Jeffrey-McNeely-09d4ccb5-4456-4f33-aea7-36f3e2ef9e43.yml, data/nc/people/Jim-Perry-111c38fc-67e4-4dfb-9d3b-3fe33fb3c8aa.yml, data/nc/people/Kristin-Baker-9f6b2b82-9747-4a89-9c58-b6580e9ca378.yml, data/nc/people/Perrin-Jones-215606a5-f44f-4e03-8617-b122900b978b.yml, data/nc/people/Rob-Bryan-26f3582f-e49c-4639-8d5b-86867de1f02c.yml, data/nc/people/Scott-Brewer-840b46bf-b314-4192-84a0-f641b13d4306.yml
added all new members of the house and senate in NC based on information from ncleg.net
=> added all NC new house members and senators

data/va/legislature/Todd-E-Pillion-0d2983ef-93a5-4d84-9fa3-2c796024562a.yml, data/va/organizations/Education-and-Health-599c50d3-04c0-41cd-9d44-db7bdacebbcd.yml, data/va/organizations/Finance-ff661479-16bf-4d59-86ce-e38e455421d9.yml, data/va/organizations/Local-Government-190564b8-309e-4828-b6cb-2475628bbb4f.yml, data/va/organizations/Rules-47de7d3f-8898-4ccd-b357-eed924dd9bd7.yml, data/va/organizations/Transportation-36d3f827-185d-4b1c-9bf6-e7c8818218e6.yml, data/va/retired/Charles-W-Carrico-Sr-23226580-5ba1-44dd-b9bd-cc06f827fcdf.yml
Closes https://github.com/openstates/issues/issues/104
1. Use `retire.py` to retire [Senator Charles W. Carrico, Sr.](https://lis.virginia.gov/cgi-bin/legp604.exe?191+mbr+S84)
1. Use `new_person.py` to add [Senator Todd E. Pillion](https://lis.virginia.gov/cgi-bin/legp604.exe?201+mbr+S111)
1. Add contact details and other required fields to the generated yaml per `schema.md`.
=> VA upper 40th dist rep change

data/fl/municipalities.yml, data/fl/municipalities/Tim-Pospichal-1eb9840d-381f-4d8a-a519-b1f08db85cd8.yml
=> Auburndale, Florida

data/az/municipalities.yml, data/az/municipalities/Christian-Price-79ccf374-a4ae-47a3-926f-28ae4d69f922.yml, data/il/municipalities.yml, data/il/municipalities/Kevin-Burns-d7d6036e-139d-4c40-9cd2-621ef9ff2bca.yml, data/nj/municipalities.yml, data/nj/municipalities/Paul-Marino-896eca46-bf7e-4451-96ab-3b21566774da.yml
- Geneva, Ill.
- Hamburg, N.J.
- Maricopa, Ariz.
=> December 8, 2020 Muni Patch

scripts/merge.py, scripts/to_yaml.py
The scripts are currently broken, due to changes in file structure and elimination of committees. This gets them going again for scraping people.
=> Fix scrape merge

data/in/legislature/Joanna-King-e2a84cfb-4ec9-4c0c-879b-27e51dbd6674.yml, data/in/retired/Christy-Stutzman-2ef0e09b-37a5-4a48-a5ad-fcaabffd3f8f.yml
Replace Stutzman with King after her resignation in December.
=> IN: Replace Stutzman with King

scripts/one-off/mayors.py
These changes were used to generate the updates in #412
=> One off mayor script updates to allow for multi-state CSV

data/ks/legislature/Aaron-Coleman-4824d856-5fdc-43a5-abee-ff60e648e112.yml
See https://twitter.com/Aaron4KS37/status/1349019093354086402, and now reflected on the House website.
=> KS: Update party for Aaron Coleman

data/ut/legislature/Derrin-R-Owens-ef1c9af3-b4f9-4eeb-b63d-a22f01c84262.yml, data/ut/legislature/J-Stuart-Adams-5b47c889-e555-4d3c-9b30-97d52ee02960.yml, data/ut/legislature/Jani-Iwamoto-738ea45e-501f-46f2-aaeb-82cef2ef95f5.yml, data/ut/legislature/John-D-Johnson-0c8df9e4-cb46-4dc1-ab5b-6d181efd58e0.yml, data/ut/legislature/Kathleen-Riebe-67c6161b-0222-4702-85ce-7409bc5bc86a.yml, data/ut/legislature/Ronald-Winterton-5079192a-3d15-4a00-b0c7-2cf29d320035.yml, data/ut/legislature/Rosemary-T-Lesser-0989a302-a2e5-4baa-a5be-42a7a20486ed.yml, data/ut/legislature/Todd-Weiler-6d49f384-ea91-41f2-b703-229a0a7452d9.yml, data/ut/retired/Lawanna-Lou-Shurtliff-b4be5b77-1d99-4c17-a387-6dab33eb56ed.yml
Replace Lawanna Shurtliff with Rosemary Lesser. Also update a few names and phone numbers. Fixes https://github.com/openstates/issues/issues/255.
=> UT: Add Rosemary Lesser

data/al/legislature/Cynthia-Almond-ad8462f8-3f3d-483e-8171-6211cd6b6bad.yml, data/al/legislature/Kyle-South-cbef3e56-a05d-4dca-8b0c-200e4bff9ad5.yml, data/al/legislature/Patrice-Mcclammy-c4b563a3-2b20-4c2d-8f54-2b7ed6a3af3f.yml, data/al/retired/Becky-Nordgren-a08f605d-221f-4d26-8e13-4bcfa964cd8e.yml, settings.yml
New legislator, retire legislator, and contact info tweaks.
=> AL: minor updates

data/az/legislature/Andrea-Dalessandro-cfdc1ced-f218-4381-b6ec-347bc963fd5d.yml, data/az/retired/Frank-Pratt-bf2e75c1-220e-4b88-9cbc-f4a4e9ddf46b.yml
Two legislators had terms accidentally removed at some point.
=> AZ: Add missing terms for Pratt and Dalessandro

data/ca/retired/David-Chiu-322fc0ac-b105-4e36-8fab-cf74b0a4e87e.yml, data/ca/retired/Ed-Chau-7a8deb33-ca1f-4c20-93b5-a16cd9536cc2.yml, data/ca/retired/Jim-Frazier-193620ba-dd85-48ff-9b0e-4611ef2d9613.yml, data/ca/retired/Lorena-Gonzalez-dfe28cb5-1e06-418d-b4dd-8328f43c2783.yml, settings.yml
4 Assembly seats are currently vacant.
=> CA: Retire 4 legislators

data/ga/committees/lower-Banks--Banking-11b1c0ee-fc7b-46d9-8d79-8fe431035e87.yml, data/ga/committees/lower-Judiciary-Non-Civil-e04489aa-cefe-4b13-adf1-309e6063da58.yml, data/ga/committees/lower-Juvenile-Justice-51dd9e40-f169-4d5a-9443-276c8a6130dc.yml
=> Remove more retired people from committees

data/ok/committees/legislature-Conference-Committee-on-State-Powers-be457191-8517-4b4e-9fac-ad30cb4111ab.yml, data/ok/committees/lower-General-Government-aa058d78-c09e-4ef0-8334-dec2241267c2.yml, data/ok/committees/lower-General-Government-edc87253-e33e-4a46-8d09-ad3720815f9d.yml, data/ok/committees/lower-Public-Safety-0b272dae-1a19-4f1b-b0d4-d7b9b3519091.yml, data/ok/committees/lower-Public-Safety-5830cdd1-7703-483d-a750-047ae44a456c.yml, data/ok/committees/lower-State-Powers-a56dd594-72cf-48eb-bead-c9d6d059a1e7.yml, data/ok/committees/lower-Transportation-cbcc6d7a-390c-4176-bc80-3d4a6f29f00c.yml, data/ok/committees/lower-Transportation-fa1bf600-b3fb-494a-92a7-6b2da48b5ef5.yml
Another place where https://github.com/openstates/issues/issues/598 is seen.
=> OK: Committee fixes

data/ri/committees/lower-Education-e80954a1-e7ed-4230-b274-d26938044fcc.yml
https://github.com/openstates/issues/issues/598
=> RI: Committee rename

data/ny/legislature/Brian-Miller-ad93da57-8a9a-4dc0-bc2c-2488c0331d16.yml, data/ny/legislature/Colin-Schmitt-fbec970d-aa83-4eed-b315-13363aa8b707.yml, data/ny/legislature/Edward-Braunstein-b7e93c8c-9a4b-4678-8d6a-effce9a76938.yml, data/ny/legislature/Emily-Gallagher-81456b86-152f-4764-a489-dade7cc572c6.yml, data/ny/legislature/Gina-Sillitti-c291848d-0879-4c0a-ae66-bc4e22a03f39.yml, data/ny/legislature/Harvey-Epstein-eaf455e1-358d-4de0-ac5d-3d8c400eb4e3.yml, data/ny/legislature/Judy-Griffin-0084a20e-9727-44d0-a60e-f074d17e65ef.yml, data/ny/legislature/Karen-McMahon-e37b1683-f103-4c4d-80bd-1b255cc1ce08.yml, data/ny/legislature/Kenny-Burgos-e2697f3d-ad8b-4c63-a39b-abac782dfe05.yml, data/ny/legislature/Khaleel-M-Anderson-cf330444-ddcb-44aa-882d-f1488c42533e.yml, data/ny/legislature/Mark-Walczyk-615c8d33-9652-4163-87b9-0fc82fc09b8c.yml, data/ny/legislature/Matthew-Simpson-22ef60e3-2d31-41a1-b063-03f307e6414e.yml, data/ny/legislature/Patricia-Fahy-a3e0c7bc-45f6-4a6b-a092-1c124c149a6d.yml, data/ny/legislature/Robert-Smullen-1aed07cb-5108-40a1-a845-93f6848062dc.yml, data/ny/legislature/Stefani-Zinerman-d4d53fcb-59b0-4869-bad8-42963b716e59.yml, data/ny/legislature/William-Barclay-285393ce-64cc-4c07-88ac-79fe18e1fc6b.yml, data/ny/retired/Carmen-De-La-Rosa-1dbb947e-e8a2-4ec9-bc5f-149b3f019afe.yml, data/ny/retired/Charles-Barron-0f494bf0-c776-4ee9-88d0-3d9e5707933f.yml, settings.yml
Two new vacancies and update contact info for some legislators.
=> NY: Vacancies and contact info updates

data/in/legislature/Carolyn-Jackson-16ded3c5-7034-4910-b5d1-76efa7b2f02f.yml, data/in/legislature/Cherrish-Pryor-8db4d04c-3afe-44c1-940b-7761cd035800.yml, data/in/legislature/Chris-Campbell-a2b2e61b-e27c-4ead-8c81-6703ea817037.yml, data/in/legislature/J-Michael-Davisson-66f9a6e4-5a92-44b0-b61b-497c94d57d49.yml, data/in/legislature/Matt-Hostettler-be7ad6b3-da1b-4b8d-b41b-6b6e48a9bdfa.yml, data/in/legislature/Michael-Crider-6ffd10c6-9fd6-4378-8841-63ce4ca88764.yml, data/in/legislature/Pat-Boy-8dde5c26-4718-45e7-a021-487d7fa6a924.yml, data/in/legislature/Philip-Boots-dd9ef5e5-8d91-4241-a31e-d2c4cfa2af02.yml, data/in/legislature/Susan-Glick-a0b2ce58-2c2d-4b71-a9e2-7b8ae153d53f.yml, data/in/legislature/Tim-OBrien-87eb34dc-70d6-4614-a871-568a836ff552.yml, data/in/legislature/Todd-Huston-d2667b82-c381-495d-b533-c70a9ae92ec0.yml, data/in/retired/Steven-Davisson-77a93fc3-bbc5-41b6-b1af-0069670dd5af.yml
Fix J. Michael Davisson, name/image/contact info updates.
=> IN: Update

data/va/legislature/Angelia-W-Graves-f747c790-f609-4da1-b125-73f1807e1430.yml, data/va/legislature/Anne-Ferrell-Tata-9fd6fbd7-5e4e-4426-9d5a-43173ab01489.yml, data/va/legislature/Briana-D-Sewell-23775904-887c-4a2c-9424-0683608193ba.yml, data/va/legislature/Elizabeth-B-Bennett-Parker-c3b0c2fc-c7bf-45f8-8ee3-50d5a57bad08.yml, data/va/legislature/Ghazala-F-Hashmi-2ae6c10e-e6d0-4033-927f-0b067b2ba0fc.yml, data/va/legislature/H-Otto-Wachsmann-Jr-496f9aa1-91ba-4386-9530-f52ea56e17bf.yml, data/va/legislature/Irene-Shin-3f02dc5d-5107-4620-add7-c32a2ea8bf44.yml, data/va/legislature/Jackie-H-Glass-dae8ce89-647a-407a-9550-60c404a89e29.yml, data/va/legislature/Jason-S-Ballard-80c98569-2ce0-44e9-8cf4-632f2dce684c.yml, data/va/legislature/Jennifer-A-Kiggans-0aea6a95-df57-407e-a70d-b809a24401a2.yml, data/va/legislature/Jennifer-B-Boysko-27eeaa71-8938-412b-90ce-f83370824485.yml, data/va/legislature/Jill-Holtzman-Vogel-26879c1b-a2e3-4423-b6b5-297a616edc3f.yml, data/va/legislature/John-J-Bell-0f319f26-2e53-45e0-a349-411d09634b5e.yml, data/va/legislature/Karen-S-Greenhalgh-2400427a-ccb1-48bb-bc70-3b99a8e502a9.yml, data/va/legislature/Kim-A-Taylor-66c4b409-9613-4d42-9d53-4adc065e3a91.yml, data/va/legislature/Marie-E-March-0806aec1-c8b9-44b1-b6c6-b45e27292c08.yml, data/va/legislature/Michelle-E-Maldonado-47e6d456-740e-4707-ae93-4b6efe8c0ce1.yml, data/va/legislature/Mike-A-Cherry-32b96a0d-662a-4c8f-9b2b-f86365640624.yml, data/va/legislature/Nadarius-E-Clark-a7fd18db-f30c-45c6-aa90-bdb6f2ce412b.yml, data/va/legislature/Phillip-A-Scott-6a07d7b6-a4b4-42f8-9a06-6a860249f5b9.yml, data/va/legislature/Scott-Wyatt-2a831795-d6fc-4635-88bf-4fd5f72ab1e7.yml, data/va/legislature/Shelly-A-Simonds-8329b3a6-9d6f-427e-9342-e53277e7c6ff.yml, data/va/legislature/Timothy-V-Anderson-c122779e-1488-4c51-9bbf-765d68ec0e41.yml, data/va/legislature/Wren-M-Williams-d3a4b614-4a6f-4b38-b3cc-8990f0f7d4d3.yml, data/va/retired/Jerrauld-C-Jay-Jones-7ef2fdd9-b55d-4ab4-83ea-17c47c2e5227.yml
Also assorted contact info updates.
=> VA: Replace Jay Jones

data/ct/legislature/Corey-P-Paris-fcc3d3fa-4b4d-4d3c-b512-003a58657a85.yml, data/ct/legislature/Dennis-Bradley-fa722794-9212-4794-b381-04d0f1d65cff.yml, data/ct/legislature/Gary-Turco-36b9eb8c-9fd8-4f6e-ba6b-fddb03bf3be3.yml, data/ct/legislature/Henri-Martin-ca8be710-988a-4415-bc37-6d3a92d1afcd.yml, data/ct/legislature/Hubert-Delany-b666accd-c7f7-41e9-ade0-f64f6e438669.yml, data/ct/legislature/Jane-M-Garibay-fee3a7d8-7e51-4c5a-af29-190694152ccc.yml, data/ct/legislature/Jeff-Currey-0589b926-29e0-4281-b0f9-73369fe7f989.yml, data/ct/legislature/Jennifer-Leeper-15c5ac01-eb03-4dd3-8ab6-d162e7420559.yml, data/ct/legislature/Kevin-C-Kelly-5acf728f-8ec5-4db5-b7eb-8dec668d0626.yml, data/ct/legislature/Mae-Flexer-77713b68-e8ef-455e-80a6-1614488fb71a.yml, data/ct/legislature/Paul-Cicarella-ca523a61-6db3-47c6-bf1f-8fd7638e999f.yml, data/ct/legislature/Quentin-W-Phipps-46678375-9195-4d3a-8aef-6476397f1491.yml, data/ct/legislature/Ryan-Fazio-c5800b0c-c84a-4e63-83fa-8aaad9b6535f.yml, data/ct/legislature/Trenee-McGee-5a41c633-8d04-43c6-b3c2-64cbbbbefcc4.yml, settings.yml
Plus various committee updates.
=> CT: Add Hubert Delany

data/or/legislature/Andrea-Valderrama-3efec526-6660-45fa-9a10-b02716b2a779.yml, data/or/legislature/Barbara-Smith-Warner-5b85821b-4b40-473b-b0a2-6a8ac013a5e8.yml, data/or/legislature/James-Hieb-d97661f8-25e9-4b1d-8ad6-25e26ea802c4.yml, data/or/legislature/Janeen-Sollman-9d3f5669-f452-4926-91ec-a74a4c4a48e5.yml, data/or/legislature/Julie-Fahey-b523dd9a-d913-4a8e-95e2-c546016f2b1a.yml, data/or/legislature/Nathan-Sosa-5615af6a-5232-45e0-b85b-bcb41e08391e.yml, data/or/legislature/Travis-Nelson-e2a96554-b503-4aad-856c-84266386e957.yml, data/or/legislature/Vikki-Breese-Iverson-a3140c7f-befe-4b83-bc54-1451b5fe00f5.yml, settings.yml
Three new legislators to fill vacancies, plus minor address updates.
=> OR: Fill vacancies

data/in/legislature/Chris-Campbell-a2b2e61b-e27c-4ead-8c81-6703ea817037.yml, data/in/legislature/Craig-Snow-d9c1cb89-9943-4afd-9353-8c771dcac356.yml, data/in/legislature/Curt-Nisly-7eb86096-7906-4bac-8bb5-98e3ecd5029c.yml, data/in/legislature/Dale-DeVon-da8afc87-2b9a-4544-8fb9-2f03f426a451.yml, data/in/legislature/David-Niezgodski-1fad6d9f-7d2c-4b2e-a74f-26a2ea44f371.yml, data/in/legislature/Eddie-Melton-c0faf1f8-7c27-46cd-9ff4-e740f4e5b376.yml, data/in/legislature/Fady-Qaddoura-ba72879f-42bd-4735-a3e0-d5edd0358f98.yml, data/in/legislature/Greg-Taylor-39798614-3cb2-40b7-adad-4f5c53ff59e5.yml, data/in/legislature/JD-Ford-85b8c0cf-3df4-45a1-8c38-d220b7122226.yml, data/in/legislature/Jack-Jordan-12a4df88-7cf2-453c-9cb8-dc5d4a2f6b55.yml, data/in/legislature/Jean-Breaux-0224fa74-0bc2-49ca-83db-03445f40b976.yml, data/in/legislature/John-Jacob-546abf56-a487-421e-b6f8-119314f528d9.yml, data/in/legislature/Kevin-Boehnlein-9b808c05-1a42-45e4-b2e8-5b91fdf759c1.yml, data/in/legislature/Lonnie-Randolph-a48f9631-3436-4445-b8fc-87c143f373cd.yml, data/in/legislature/Michael-Griffin-ac21d493-d65d-4101-b164-5e64b185c259.yml, data/in/legislature/Rodney-Pol-4058ba4c-30a9-46a7-80a1-1f3de1e44a2f.yml, data/in/legislature/Shelli-Yoder-872447dd-3b06-421e-af8c-25ea68aa5ae4.yml, data/in/legislature/Timothy-Lanane-cf84a4e4-8c27-420d-a69d-af4bb78a5f72.yml, data/in/legislature/Timothy-Wesco-fbcd4d2c-32c6-4c97-837b-4e4ed80c43df.yml, data/in/retired/Erin-Houchin-05cfdc73-ff21-4d74-833e-e3da82ed7509.yml, data/in/retired/Frank-Mrvan-7dacbdba-68ea-4b74-8864-d1b19a1ff4c0.yml, settings.yml
Also update websites/images/contact info.
=> IN: Retirements and new legislator

data/ma/legislature/Andres-X-Vargas-c1f81bec-d032-4f41-940c-ca32f2b5af12.yml, data/ma/legislature/Brendan-P-Crighton-77994b2c-f88c-4a5f-bf9d-7abd1875d8dc.yml, data/ma/legislature/Bruce-J-Ayers-f81b07bd-cc43-47be-95ea-dca26f19a647.yml, data/ma/legislature/Christine-P-Barber-35396516-6096-4336-ab74-80d6d8e53bcd.yml, data/ma/legislature/Christopher-M-Markey-560c5ca3-d9b4-4c47-998c-a9baa16a8309.yml, data/ma/legislature/Cindy-F-Friedman-456b0061-febd-4ff7-8547-42be0685526f.yml, data/ma/legislature/Daniel-J-Ryan-c0519476-08fc-44af-9114-c77d197f883d.yml, data/ma/legislature/Daniel-M-Donahue-d70e97f1-b8ec-489d-ab5a-2b7f3775ae8a.yml, data/ma/legislature/David-M-Rogers-51adc4d9-23d8-442f-b692-c4e4204f552e.yml, data/ma/legislature/David-Paul-Linsky-06867e5f-9de5-4cb2-a3ae-a039e890718c.yml, data/ma/legislature/Denise-C-Garlick-7be05b7f-d3dd-4a0f-b7d0-f29144d47f92.yml, data/ma/legislature/Jamie-Zahlaway-Belsito-ec6ea7c7-5e71-4f0e-a151-92d2f83c99b2.yml, data/ma/legislature/Jay-D-Livingstone-033bf9eb-2706-4c5f-9f93-8e8d222bf2c0.yml, data/ma/legislature/Jerald-A-Parisella-67833a9e-e086-4494-a364-fecdcd6aa609.yml, data/ma/legislature/Kenneth-I-Gordon-47c42957-b618-41b7-a557-5d24c33568cf.yml, data/ma/legislature/Lydia-Edwards-5278711f-55ec-4a67-acc9-edd1db1c4e8c.yml, data/ma/legislature/Michael-F-Rush-6a82d675-3496-48af-88cf-23c26355b01f.yml, data/ma/legislature/Michael-J-Soter-4cec2aa4-c17b-4749-b0e9-58a25695bf2f.yml, data/ma/legislature/Thomas-P-Walsh-5f796cb3-08ae-40c4-8c11-a2758f317cc2.yml, data/ma/retired/Bradford-R-Hill-6e64e8db-c1f5-4f72-994b-dbe9cfdab8a5.yml, data/ma/retired/Carolyn-C-Dykema-1368c833-35b4-4cf3-9bb4-e9e41d1434f7.yml, data/ma/retired/Claire-D-Cronin-8535e83a-df7d-4c14-9a19-1f32fd2147cb.yml, data/ma/retired/Joseph-A-Boncore-9a5a1e33-a7d4-45c2-93cb-3c1bc630fbe2.yml, data/ma/retired/Lori-A-Ehrlich-9f7305fa-a7b5-4931-98fc-621a53d3717b.yml, settings.yml
Assorted contact info updates as well.
=> MA: 5 retirements, 2 new legislators

data/nc/legislature/Abe-Jones-559521af-e5f9-43c3-a75e-de9b242d364f.yml, data/nc/legislature/Brenden-H-Jones-1e419504-9efe-4b1f-b1e0-6e8d7d8c74a9.yml, data/nc/legislature/Brent-Jackson-23f1da0b-34b2-4347-adb4-f5fc26e0475d.yml, data/nc/legislature/Brian-Farkas-41f33856-373b-41a7-b318-d03ce9db476e.yml, data/nc/legislature/Caleb-Rudow-a47657b4-dcb7-452d-876f-b7cddcf194a9.yml, data/nc/legislature/Dean-Arp-ffdbb3fa-0445-460a-9501-18b5028fbe50.yml, data/nc/legislature/Destin-Hall-636555c9-b55c-47f8-9fcc-c9cb93b27f50.yml, data/nc/legislature/Donna-McDowell-White-7e1cb220-ff5e-4543-bc51-f44ba7ee0a2b.yml, data/nc/legislature/Howard-J-Hunter-III-82c54a54-0f6e-4fa9-95ec-34f67abcc238.yml, data/nc/legislature/Jason-Saine-bbb0290b-f3f6-4e3b-a171-9c41d5f70abd.yml, data/nc/legislature/Jim-Burgin-9793e1e4-641c-4a5c-b1bc-7f6d0a65a655.yml, data/nc/legislature/Kristin-Baker-9f6b2b82-9747-4a89-9c58-b6580e9ca378.yml, data/nc/legislature/Mujtaba-A-Mohammed-c733e47e-af6a-4f31-a350-010043b5164b.yml, data/nc/legislature/Steve-Jarvis-d0af18d6-b4e1-4a9a-92f3-a6950961e953.yml, data/nc/legislature/Sydney-Batch-f29f268e-5a29-4f49-8c5e-3fa19688f4a2.yml, data/nc/legislature/Vernetta-Alston-baca6c05-f6c5-4239-bf9b-c4f57001273d.yml, data/nc/legislature/Vickie-Sawyer-ece1f23b-841d-4145-9719-3807bf29f861.yml, data/nc/retired/Susan-C-Fisher-ea05fa3b-719a-4271-8684-9712537bc839.yml
Updates to legislative assistants as well.
=> NC: Replace Fisher with Rudow

data/in/legislature/Gary-Byrne-aa12c3a4-7207-4474-af92-7a1f9dcf62a3.yml, data/in/legislature/J-Michael-Davisson-66f9a6e4-5a92-44b0-b61b-497c94d57d49.yml, data/in/legislature/Tim-OBrien-87eb34dc-70d6-4614-a871-568a836ff552.yml, settings.yml
Also add other names for O'Brien and Davisson.
=> IN: Add Gary Byrne

poetry.lock
Pull in fix for committee database updates.
=> openstates 6.10.9

data/wa/legislature/Ann-Rivers-e8716b1c-7767-4a07-b0a8-346e6fe175f5.yml, data/wa/legislature/Brandy-Donaghy-0f60580f-c121-4661-ae02-5acdfb3923d8.yml, data/wa/legislature/Curtis-King-a8e7617c-7cbb-45ed-a577-3dd7341a3bd7.yml, data/wa/legislature/Dan-Bronoske-ff625fe2-be44-459e-8361-73af49b48fbc.yml, data/wa/legislature/Emily-Randall-f93ca36c-e072-46a3-a70a-2605b425517e.yml, data/wa/legislature/JT-Wilcox-d3572bf1-190b-4170-8ffd-1d9dd77c1fe4.yml, data/wa/legislature/Jake-Fey-4ed1ee96-ea0f-4fc6-9c74-14cea6328716.yml, data/wa/legislature/Jamie-Pedersen-f6d8dcb4-c212-4f2b-a043-a541e47dede0.yml, data/wa/legislature/Jeremie-Dufault-2dce9967-a2fc-4211-9b1a-bce3b4f32a09.yml, data/wa/legislature/Joe-Nguyen-f7511475-21ef-4127-bc59-f5e7b76f2579.yml, data/wa/legislature/John-Lovick-9849a792-2307-40c8-97ae-388d731fa89b.yml, data/wa/legislature/Judy-Warnick-cce36d0b-a3d8-4375-bf70-06760a2eebc3.yml, data/wa/legislature/Lisa-Wellman-0c274c6c-6813-4a77-b7ed-5576e9989493.yml, data/wa/legislature/Liz-Lovelett-f82a6162-120e-4bf2-90c4-02e22278d96e.yml, data/wa/legislature/Mike-Sells-0624d2f7-2e8d-4d6f-8eb2-e2c8f604e55a.yml, data/wa/legislature/Perry-Dozier-b7caabda-31e5-48b5-a4b1-82d2bffae0ae.yml, data/wa/legislature/Ron-Muzzall-57efa2de-d8dc-4d0b-92a3-7ca12549c339.yml, data/wa/legislature/Simon-Sefzik-e512114b-7fd9-47fa-8ed0-7a81a0072c4e.yml, data/wa/legislature/Tina-Orwall-ef711ad1-b4e6-44c9-a971-7d57e8140f04.yml, data/wa/legislature/Twina-Nobles-dd5d76ce-7efe-4c95-aae3-a59a4676fe78.yml, data/wa/legislature/Yasmin-Trudeau-28de7c48-9b66-4597-a15f-ce7b132fba5a.yml, data/wa/retired/Doug-Ericksen-bd0ebce5-e0eb-46b4-bc52-3b0ac3b41c0a.yml, data/wa/retired/Steve-Hobbs-14816361-a653-4221-9673-416581c9d97d.yml
=> WA: Replace 3 legislators

data/ca/legislature/Mike-Fong-3a7bde9c-8709-49c7-89e4-0835ea1f9eb6.yml, data/ca/legislature/Rosilicie-Ochoa-Bogh-cb5b9356-6798-44d2-8dc2-caf5651ac4e3.yml, data/ct/legislature/Amy-Morrin-Bello-ff1c4d90-5cc3-4ff9-8f31-454d03803816.yml, data/ct/legislature/Corey-P-Paris-fcc3d3fa-4b4d-4d3c-b512-003a58657a85.yml, data/ct/legislature/Gary-Turco-36b9eb8c-9fd8-4f6e-ba6b-fddb03bf3be3.yml, data/ct/legislature/Geoff-Luxenberg-37f6cb6c-888c-44c1-8c21-b273d967a62d.yml, data/ct/legislature/Henri-Martin-ca8be710-988a-4415-bc37-6d3a92d1afcd.yml, data/ct/legislature/Hubert-Delany-b666accd-c7f7-41e9-ade0-f64f6e438669.yml, data/ct/legislature/Jennifer-Leeper-15c5ac01-eb03-4dd3-8ab6-d162e7420559.yml, data/ct/legislature/Kevin-C-Kelly-5acf728f-8ec5-4db5-b7eb-8dec668d0626.yml, data/ct/legislature/Michael-DiGiovancarlo-1e5a518e-ddf5-4976-b239-9a5324339a47.yml, data/ct/legislature/Patricia-Billie-Miller-fcf63a22-3979-4cbf-a719-0d414d13e1ac.yml, data/ct/legislature/Paul-Cicarella-ca523a61-6db3-47c6-bf1f-8fd7638e999f.yml, data/ct/legislature/Quentin-W-Phipps-46678375-9195-4d3a-8aef-6476397f1491.yml, data/ct/legislature/Rick-Lopes-bdc5f5a0-0285-45d2-a6fd-d29d8b31cd43.yml, data/ct/legislature/Robin-Green-f664d091-23ab-46d0-a019-6009e0480a81.yml, data/ct/legislature/Ryan-Fazio-c5800b0c-c84a-4e63-83fa-8aaad9b6535f.yml, data/ct/legislature/Stephen-R-Meskers-77dbf0fd-d45c-445c-9966-0135fff8feaa.yml, data/ct/legislature/Tammy-R-Exum-8872e78b-25b4-406b-84b2-949c700f7b56.yml, data/ct/legislature/Trenee-McGee-5a41c633-8d04-43c6-b3c2-64cbbbbefcc4.yml, data/ct/legislature/William-Pizzuto-f7127b57-a72f-4b84-abf6-77b021cddf3f.yml, settings.yml
Also some updates to contact info/extras.
=> CA, CT: Add newly elected legislators

data/co/legislature/Andres-Pico-51a7c065-0653-4031-a198-6af1b444c9eb.yml, data/co/legislature/Andrew-Boesenecker-278f042b-4fe3-4325-ad59-bc240e4fda0c.yml, data/co/legislature/Barbara-Kirkmeyer-6d1fcaf0-ed3d-4772-876f-09dc5e931556.yml, data/co/legislature/Chris-Kolker-f72691ec-a5a0-413b-a344-e452009551a2.yml, data/co/legislature/Cleave-Simpson-715df6f2-cef6-4b88-b745-0207c8ffb4ff.yml, data/co/legislature/Dan-Woog-df050043-0b4f-4b51-8df0-ffd6cd6cd5b2.yml, data/co/legislature/David-Ortiz-67afefca-857c-4feb-8739-f7c68d6e6b71.yml, data/co/legislature/Dominick-Moreno-698cdd09-6b39-4e6b-bdc7-5f8529a74c6e.yml, data/co/legislature/Faith-Winter-d8091b89-e076-404f-a2a3-886f5cb9b89c.yml, data/co/legislature/Iman-Jodeh-506f18ea-3611-408b-aa0e-73adf9681efe.yml, data/co/legislature/James-Coleman-e4e1f1a9-7134-4d90-9fed-2aa7a0e3a307.yml, data/co/legislature/Jennifer-Bacon-4aba3e11-9554-405d-b926-5435eb77fa26.yml, data/co/legislature/Judy-Amabile-829879ea-a9a3-42b6-8f5f-d209b1cc961d.yml, data/co/legislature/Karen-McCormick-7631027c-2467-4112-8f03-abad6c6ed8f2.yml, data/co/legislature/Kyle-Mullica-ebf0c3de-2f58-436f-af67-12863f9cb552.yml, data/co/legislature/Lindsey-Daugherty-2de0a3a1-a1e3-477f-88b9-3212fa52fb9c.yml, data/co/legislature/Mandy-Lindsay-2582d3dd-20c0-4d15-83a0-3b6dab1e98d2.yml, data/co/legislature/Mary-Bradfield-9e1ed481-cc42-4186-a8fe-891abba60162.yml, data/co/legislature/Mike-Lynch-551d839e-de95-4f9f-bb64-a36bb05fa396.yml, data/co/legislature/Naquetta-Ricks-64f01ef4-238f-4e48-9657-e221e0d030c0.yml, data/co/legislature/Nick-Hinrichsen-4d753f6e-b7e3-420d-a684-e9a27f7ab27b.yml, data/co/legislature/Ron-Hanks-df1c81d9-286c-45f4-9cb4-830d29aa0842.yml, data/co/legislature/Shane-Sandridge-530a13be-91ef-448e-b874-ae4df7e776e4.yml, data/co/legislature/Stephanie-Luck-bf7f0f6f-82b3-4eeb-b7c4-f9fc4213b52c.yml, data/co/legislature/Stephen-Fenberg-cda35383-f5af-40b7-ab1f-41798fe6444e.yml, data/co/legislature/Tom-Sullivan-7a09a2fa-0249-4751-8dd1-caa100395438.yml, data/co/legislature/Tonya-Van-Beber-5f439172-7cc6-4e77-b010-c89668ff36df.yml, data/co/legislature/Tracey-Bernett-8b99eb49-4a1e-448c-88be-0450874f54a9.yml, data/co/retired/Dominique-Jackson-afc98d85-24dd-4dc8-9552-3d7f76f7d697.yml, data/co/retired/Leroy-Garcia-6aa0113f-e293-4be5-b0e2-715581e84878.yml
Also various updates to images and leadership titles.
=> CO: Replace 2 legislators

data/ct/legislature/Hubert-Delany-b666accd-c7f7-41e9-ade0-f64f6e438669.yml, data/ct/legislature/Maryam-Khan-298d6d03-248e-44c2-be42-269bc417745c.yml, data/ct/legislature/Ronald-A-Napoli-Jr-71fb3504-679f-419d-86bf-d1ae7d573244.yml, data/ct/legislature/Tammy-R-Exum-8872e78b-25b4-406b-84b2-949c700f7b56.yml, data/ct/legislature/William-Pizzuto-f7127b57-a72f-4b84-abf6-77b021cddf3f.yml, data/fl/legislature/Jervonte-Tae-Edmonds-bb2ae855-2e7a-4744-9271-a8ae1af89428.yml, data/fl/legislature/Joseph-A-Joe-Casello-de6ef298-c7dd-4a60-866e-763e2c5bf607.yml, data/fl/legislature/Rosalind-Osgood-ba43e456-b4d3-408d-aeba-d4b7482dacd0.yml, data/fl/retired/Rene-Coach-P-Plasencia-32888a93-b636-4c26-963b-2467072826e4.yml, settings.yml
A few assorted name/contact info updates as well.
=> CT, FL: Fill vacancies

data/wi/municipalities/Cavalier-Johnson-fe397c40-e3ed-41a9-b43e-7a64b69b23f6.yml
Was re-elected in a special after being appointed temporarily after Barrett resigned.
=> Update MKE Mayor (Cavalier Johnson)

data/sd/legislature/V-J-Smith-4f30fe3c-f980-4711-b65c-41608c01b99f.yml, data/tn/legislature/Cameron-Sexton-421c9380-99f4-47ff-9d70-5c5eced05a89.yml
Fix for SD people data on VJ Smith
https://github.com/openstates/issues/issues/655
=> Fix duplicate middle initial

data/ca/legislature/Benjamin-Allen-e725b91e-1f7f-4510-a9cc-0b9a39d283c3.yml, data/ca/legislature/Lori-D-Wilson-926d1337-0318-4c12-a291-178f10199b23.yml, data/nd/legislature/Cole-Conley-3b75961c-1c9e-4150-84ee-965ffb59fafa.yml, data/nd/legislature/Tracy-Potter-497f65ef-8169-4d4c-b420-7f48a21d94f1.yml, data/nd/retired/Erin-Oban-77fa57fe-026b-470c-a694-25211b9801a8.yml, settings.yml
Add new legislator in CA, replace one in ND.
=> CA, ND: Add new legislators

.github/CODEOWNERS, data/ca/legislature/Benjamin-Allen-e725b91e-1f7f-4510-a9cc-0b9a39d283c3.yml, data/ca/legislature/Lori-D-Wilson-926d1337-0318-4c12-a291-178f10199b23.yml, data/nd/legislature/Cole-Conley-3b75961c-1c9e-4150-84ee-965ffb59fafa.yml, data/nd/legislature/Tracy-Potter-497f65ef-8169-4d4c-b420-7f48a21d94f1.yml, data/nd/retired/Erin-Oban-77fa57fe-026b-470c-a694-25211b9801a8.yml, data/vt/legislature/Linda-Joy-Sullivan-bf91c530-54d5-4984-93ea-e12113eb975b.yml, data/vt/legislature/Mark-A-MacDonald-a2922c8e-7f90-44ec-a5e6-63daf45d9c25.yml, settings.yml
Testing this out to see if it works better for PRs
=> Create CODEOWNERS file

settings.yml
Scraper still fails since there aren't links for the representatives yet, will keep eye out for updates to source page
=> MI: Update Vacancies

data/ny/legislature/Andrew-Hevesi-2a9aad09-337f-4fd0-8e87-70afd78ac8cc.yml, data/ny/legislature/Ari-Brown-38ed0365-1654-4a2d-bb23-4428736df57f.yml, data/ny/legislature/Brian-Cunningham-27a087c4-fad6-4245-b680-20aff5c3251c.yml, data/ny/legislature/Monique-Chandler-Waterman-24fb9f1e-0bd6-4ac2-8a49-1091016863d2.yml, data/ny/legislature/Ron-Kim-f8732ad5-c692-4bab-bbaa-fb772a031a5d.yml, data/sc/legislature/David-R-Hiott-14b0abeb-70fd-404b-9f55-ff2e75e2c7ef.yml, data/sc/legislature/G-Murrell-Smith-Jr-bc549137-780f-4b77-9438-61a92d3dce48.yml, data/sc/legislature/J-Anne-Parks-1ee1c7ea-73f4-4a0a-a16a-f802692f75c3.yml, data/sc/legislature/J-Gary-Simrill-99ada22b-98f9-400c-b0cf-1a548ed72257.yml, data/sc/legislature/James-H-Jay-Lucas-f9b167fd-3547-4aad-b290-13b05bb35228.yml, data/sc/legislature/Mike-Reichenbach-c2a237ba-67b6-4280-9cf2-430f1d10d28e.yml, data/sc/legislature/Robby-Robbins-ea7da5ce-c132-44b0-8b3c-33745f9d3e4b.yml, data/sc/legislature/T-Alan-Morgan-10d51991-3dec-499f-8ed2-9c5685de9b00.yml, settings.yml
Assorted contact info updates.
=> NY, SC: Fill vacancies

data/me/legislature/Braden-Sharpe-40afa5fa-8599-4927-83a4-20afac7e7a0e.yml, data/me/legislature/Danny-Edward-Costain-a93d36ff-25db-4f7f-b28c-7b3c00867c3c.yml, data/me/legislature/Joseph-F-Underwood-b6102f7e-216a-4632-901c-25b2b446f080.yml, data/me/legislature/Kristi-Michele-Mathieson-375e5fda-9367-4ce3-a209-1c772c32219f.yml, data/me/legislature/Nicole-Grohoski-e53a09e6-a38e-4622-97e4-c40bf2d93faa.yml, data/me/legislature/Rebecca-J-Millett-1c0f311a-f4ab-4091-aaa0-9b0de3612e9e.yml, data/me/legislature/Richard-G-Mason-6c313875-2dc9-4ef5-b869-c3cc0b7d5c97.yml, data/me/retired/Genevieve-McDonald-80d82f32-3efd-4b95-a2b9-e459c810edb0.yml, data/me/retired/Jeffery-Allen-Gifford-a1410a36-bd90-4855-b260-c5c13b402301.yml, settings.yml
Along with two retirements and contact info updates.
=> ME: Nicole Grohoski from House to Senate

data/ny/legislature/Demond-Meeks-34f326e1-6e7e-40b2-9ece-10856986cb1b.yml, data/ny/legislature/Edward-A-Rath-III-2f73eb9e-bea3-48d8-a2b2-740dc12f12b7.yml, data/ny/legislature/Jamaal-T-Bailey-6872ad9e-fcba-426f-a9ef-b4495dba17f5.yml, data/ny/legislature/James-Sanders-Jr-e00ee209-a6a5-4ca1-8ac6-f403e1cbcca2.yml, data/ny/legislature/James-Skoufis-c1f048f2-6e1d-4e1b-b161-d97e2f16c1f8.yml, data/ny/legislature/Jessica-Ramos-a0b3e01c-d323-4624-a0da-6a1e2b0dfb31.yml, data/ny/legislature/John-W-Mannion-fcfe534b-e6d4-4066-83c0-6d0d617aab82.yml, data/ny/legislature/Mario-R-Mattera-04f9beb9-b562-4f2f-9f23-4856fe0fd0dc.yml, data/ny/legislature/Michaelle-Solages-2cb280b3-0aa9-4a76-abfd-3118e0d96a08.yml, data/ny/legislature/Monique-Chandler-Waterman-24fb9f1e-0bd6-4ac2-8a49-1091016863d2.yml, data/ny/legislature/Peter-Oberacker-fe80b36a-56ba-49d6-a14c-05f35ba6f610.yml, data/ny/legislature/Sean-M-Ryan-6913e7e0-3ad5-4593-a2b0-dc31e974cdf6.yml, data/ny/legislature/Shelley-Mayer-a9b13089-77fc-4e9d-a9e4-35933ea903a0.yml
Mostly updates offices and photos
=> NY: update legislators

data/ia/municipalities.yml, data/ia/municipalities/Pam-Soseman-85d7d07e-f23f-4718-8043-86dd0bf4dce0.yml, data/ma/municipalities.yml, data/ma/municipalities/Gina-Louise-Sciarra-d094318f-eec5-4ad3-b249-f87e0c8bb979.yml, data/ma/municipalities/Jennifer-Macksey-42029ac6-7c33-4fdc-b016-26f974457ca7.yml, data/ma/retired/David-J-Narkewicz-1602c8e0-d2d4-48ed-9c49-5e9c09cad12d.yml, data/mi/municipalities.yml, data/mi/municipalities/D-Wayne-ONeil-ff055879-f09f-46a4-b04f-6f20c66c3074.yml, data/mi/municipalities/Paul-Frechette-a86ed6e7-e2f7-4979-9902-7f86d52fad30.yml, data/ny/municipalities.yml, data/ny/municipalities/Bruce-Blakeman-ddac2f65-b2bd-4b4f-a84e-f69091a15b7e.yml, data/ny/municipalities/Joel-Griffin-6a84613f-6878-4ffe-b47a-d4ccab386624.yml, data/pa/municipalities.yml, data/pa/municipalities/Lance-E-Colondo-9b9af45d-2514-4cce-bd3a-faf2df2ef505.yml, data/pa/municipalities/Matthew-Wismer-d0118143-7e94-438b-9f44-499f61797fdd.yml, data/sc/municipalities.yml, data/sc/municipalities/Gregory-Habib-cdf83838-b3ef-4ebe-808e-504f9aaeb829.yml
I'm helping out resistbot by loading some people updates.  
There's both a retirement (`David-J-Narkewicz-1602c8e0-d2d4-48ed-9c49-5e9c09cad12d.yml` and an retirement (`Matthew-Wismer-d0118143-7e94-438b-9f44-499f61797fdd.yml`) in this batch; hopefully I handled them correctly.
=> Update mayors (SC, NY, IA, MI, PA, MA)

data/fl/municipalities/Ken-Welch-af5ebc49-e667-4ed7-acc2-725eda35091d.yml
Saint Petersburg has had a new Mayor since January 6, added here.
=> Add Mayor of St. Petersburg, Fla.

data/dc/executive/Alice-Miller-8f0e4b63-52bc-4d4b-b6e6-83fce260fc6c.yml, data/dc/executive/Muriel-Bowser-dce9c4a8-218a-411d-bb93-09f7e8347d8c.yml, data/dc/legislature/Anita-Bonds-860fa95b-c737-43bd-948d-1dd6dc1b734e.yml, data/dc/legislature/Brianne-K-Nadeau-4e806a33-bba3-4484-95f8-d723769b99f1.yml, data/dc/legislature/Brooke-Pinto-bf329860-076e-4d14-bed2-969d0d13dfec.yml, data/dc/legislature/Charles-Allen-ab8e39c8-583e-4e9d-b481-0f43c21318ba.yml, data/dc/legislature/Christina-Henderson-43dcb6c4-0eb1-48c7-965b-4979eb747b5b.yml, data/dc/legislature/Elissa-Silverman-438f747e-7345-47f9-ba1b-bb20c8844383.yml, data/dc/legislature/Janeese-Lewis-George-4fc6d65b-d6d2-46d7-bdea-48b5458576ab.yml, data/dc/legislature/Kenyan-McDuffie-cc7796a1-6644-4bc1-a536-b9307e84b22f.yml, data/dc/legislature/Mary-Cheh-d47c1f12-7a5a-417a-b458-7f7a086e7d4c.yml, data/dc/legislature/Phil-Mendelson-e3b9567d-67ff-4cc1-89eb-1ed1af646393.yml, data/dc/legislature/Robert-C-White-Jr-07b9c384-a232-40d5-b445-61db9e4bb65b.yml, data/dc/legislature/Trayon-White-8c48b12b-59a2-41bb-96c5-fc3b367637aa.yml, data/dc/legislature/Vincent-Gray-23ff0b28-93f2-45a2-8afc-ce7f8e5cdf19.yml
=> Update People DC

settings.yml
=> MULTI: update vacancies

poetry.lock
Signed-off-by: John Seekins <john@civiceagle.com>
=> update openstates-core (and deps)

poetry.lock
Signed-off-by: John Seekins <john@civiceagle.com>
=> update os-core to handle missing keys in US people

data/pa/retired/David-R-Millard-1ef8fc41-4dde-431a-b771-98dd465f5683.yml
=> PA Date Fix

data/nj/legislature/Kim-Eulner-7d1446e7-5dd0-4c1a-b85c-033c7a693838.yml
Should fix the issue with Save to DB actions right now
=> NJ: fix deleted duplicate id

.github/workflows/lint-yaml.yml
Signed-off-by: John Seekins <john@civiceagle.com>
=> disable people linting

data/il/committees/upper-Agriculture-110f79bb-27f4-462d-9c57-59aeecfb63a0.yml, data/il/committees/upper-Approp--Health-and-Human-e72e72e2-810d-45c6-8827-a48b04ef4174.yml, data/il/committees/upper-Approp--Pub-Safety--Infrastructure-b0daddd5-e80f-4c43-8eb3-56cb3d132de6.yml, data/il/committees/upper-Approp-Ed-f71fe8bf-b40c-4e4b-88e3-4d1894a8ce9b.yml, data/il/committees/upper-Appropriations-96c39c15-dd2d-4b3e-98be-2e591726c950.yml, data/il/committees/upper-Assignments-0c8fa931-94b6-4f3b-85b1-1e8ab5a7e583.yml, data/il/committees/upper-Behavioral-and-Mental-Health-e3f6a452-462f-461f-a067-9e6eb4116f72.yml, data/il/committees/upper-Early-Childhood-Education-a5f467b2-c655-432d-9578-8e72aa17e039.yml, data/il/committees/upper-Education-99de4992-475f-4b22-ab0b-522f307fd679.yml, data/il/committees/upper-Energy-and-Public-Utilities-716ddc1b-4917-4d41-85df-a0fd5d4220dc.yml, data/il/committees/upper-Environment-and-Conservation-eea8ca39-495a-451e-bc3c-d474d257116f.yml, data/il/committees/upper-Executive-Appointments-c0e0f5aa-b190-47ed-a37c-2bcb4609f840.yml, data/il/committees/upper-Executive-e0ae0b47-b092-455d-ab81-e4946e1a37b1.yml, data/il/committees/upper-Financial-Institutions-a8ee72ac-a8a6-4085-b583-d2030f3187de.yml, data/il/committees/upper-Health-and-Human-Services-3ba9bf65-03ec-4cdb-abe3-9d54518bb75b.yml, data/il/committees/upper-Higher-Education-9f563e13-71fb-4663-b854-e23d4557ea57.yml, data/il/committees/upper-Human-Rights-0e5c4f7f-0f3b-43bf-8b52-a672545a30ca.yml, data/il/committees/upper-Insurance-ec1a9b64-fe7b-4ffb-9490-63118a6e57f5.yml, data/il/committees/upper-Judiciary-df75c71a-5784-4e17-a208-23cbd0bb5caf.yml, data/il/committees/upper-Labor-eebe2944-9538-40c4-b489-5798547f39ea.yml, data/il/committees/upper-Licensed-Activities-b8211b06-4d5d-4822-bcb9-f9b2ed7db170.yml, data/il/committees/upper-Local-Government-21cb8c0b-cf4b-4fab-8637-21627a25811b.yml, data/il/committees/upper-Public-Health-a70c04e0-f599-46b2-969a-049d9adfa9a5.yml, data/il/committees/upper-Revenue-c31abd6e-c6ae-4be8-b723-7ec9fa58c259.yml, data/il/committees/upper-Special-Committee-on-Pensions-f606ccdc-0dde-4c70-843e-0aeaf02afb70.yml, data/il/committees/upper-State-Government-8515d62e-47f6-4af2-9a95-98c00d81f3f7.yml, data/il/committees/upper-Transportation-6f0f2540-832c-4aea-a475-d9e90fe14f56.yml, data/il/committees/upper-Veterans-Affairs-3bcfcc8e-7bfe-4f1c-a056-64f981084c2b.yml
Senate committees for IL. I believe IL general assembly is still adding information because there aren't any subcommittees listed for the senate and there aren't any committees at all listed for the house.
=> IL: senate committees

data/md/legislature/William-G-Folden-d8938e62-87cd-420e-a009-f78a418ed138.yml
Should fix [this error](https://github.com/openstates/people/actions/runs/4166886920/jobs/7211789128) on the database update.
=> Add old os identifier to Sen Folden

data/nh/legislature/Clifford-A-Newton-29d53319-cb0c-4b0c-bfac-14a694226bb8.yml, data/nh/legislature/Timothy-Lang-5330ad05-ce69-47c0-9093-6286233c7a7d.yml
Helps fix [this error](https://github.com/openstates/people/actions/runs/4167282508/jobs/7212677029) in the Update DB step
=> NH: add old OS identifiers

data/vt/legislature/Robin-Chesnut-Tangerman-2f45cec4-4094-4a82-a11e-66e8527bb0d0.yml
Fixes [this issue](https://github.com/openstates/people/actions/runs/4169110968/jobs/7216686173) on Update action
=> VT: add missing id

data/wv/legislature/Rupert-Phillips-c1187148-471e-4bdc-acf5-16fa0d5d998e.yml
Should fix [this one](https://github.com/openstates/people/actions/runs/4176062814)
=> WV: add old OS id

data/co/legislature/Kyle-Brown-f376a75e-e0b0-4bf7-95b1-0931ade3bdb8.yml, data/co/retired/Tracey-Bernett-8b99eb49-4a1e-448c-88be-0450874f54a9.yml
Fix for [OS-1059](https://civic-eagle.atlassian.net/browse/OS-1059) (retired a legislator who resigned and added the legislator who's serving as replacement).
=> CO: people update

data/wa/legislature/Lillian-Ortiz-Self-09d83bae-b84b-436e-8d7f-5cebc05e74a3.yml, data/wa/legislature/Twina-Nobles-dd5d76ce-7efe-4c95-aae3-a59a4676fe78.yml
Fixes for [OS-1157](https://civic-eagle.atlassian.net/browse/OS-1157) and [DATA-2437](https://civic-eagle.atlassian.net/browse/DATA-2437).
=> WA: people data fixes

data/ar/legislature/Deborah-Ferguson-e91e8723-8f91-4702-8680-f40d181b52f6.yml, data/ar/retired/Stu-Smith-86cb8c59-535b-47cb-871e-2972d7009bb9.yml
Fix for [OS-1142](https://civic-eagle.atlassian.net/browse/OS-1142)
=> AR: fixing legislators' positions

data/dc/legislature/Anita-Bonds-860fa95b-c737-43bd-948d-1dd6dc1b734e.yml, data/dc/legislature/Brianne-K-Nadeau-4e806a33-bba3-4484-95f8-d723769b99f1.yml, data/dc/legislature/Brooke-Pinto-bf329860-076e-4d14-bed2-969d0d13dfec.yml, data/dc/legislature/Christina-Henderson-43dcb6c4-0eb1-48c7-965b-4979eb747b5b.yml, data/dc/legislature/Kenyan-McDuffie-cc7796a1-6644-4bc1-a536-b9307e84b22f.yml, data/dc/legislature/Matthew-Frumin-3451eb73-5042-4269-91b5-0287e527e72e.yml, data/dc/legislature/Robert-C-White-Jr-07b9c384-a232-40d5-b445-61db9e4bb65b.yml, data/dc/legislature/Vincent-Gray-23ff0b28-93f2-45a2-8afc-ce7f8e5cdf19.yml, data/dc/legislature/Zachary-Parker-30cb555a-f684-418e-8b63-8101e7a34552.yml, data/dc/retired/Elissa-Silverman-438f747e-7345-47f9-ba1b-bb20c8844383.yml, data/dc/retired/Mary-Cheh-d47c1f12-7a5a-417a-b458-7f7a086e7d4c.yml
Updating people data to reflect recently retired legislators and party changes. Relates to [OS-1062](https://civic-eagle.atlassian.net/browse/OS-1062).
=> DC: people data update

data/ct/legislature/Minnie-Gonzalez-57900db1-ade5-4107-8025-a0c664f41a32.yml, data/ct/legislature/Raghib-Allie-Brennan-1a01451b-8c85-4bde-9cef-ab083d99ae84.yml, data/ct/legislature/Rob-Sampson-0cdb540d-c360-4981-b7a9-2a67e2f91121.yml
Minor fixes related to [OS-1106](https://civic-eagle.atlassian.net/browse/OS-1106).
=> CT: minor fixes for legislators

data/ky/legislature/Cassie-Chambers-Armstrong-8dbecabb-ef15-4925-8e50-26331e738a05.yml, data/ky/legislature/Shelley-Funke-Frommeyer-b7112818-3357-413d-acae-a46bf3442b1d.yml, data/ky/retired/Morgan-McGarvey-9983a801-0a07-4d17-bca0-afb9576ebe69.yml, data/ky/retired/Ralph-Alvarado-c2d18e4a-15c9-440c-9bec-f533a03b4235.yml, settings.yml
Retiring and adding new legislators, as detailed on [OS-1136](https://civic-eagle.atlassian.net/browse/OS-1136) and [OS-1137](https://civic-eagle.atlassian.net/browse/OS-1137)
=> KY: people data fixes

data/wv/legislature/Trenton-Barnhart-4a909c49-37c6-4105-ac77-afe4745a1b1b.yml
Fixing delegate contact info as detailed in [OS-1147](https://civic-eagle.atlassian.net/browse/OS-1136)
=> WV: fixing delegate contact info

data/vt/executive/Jim-Condos-74d1d02c-adde-4780-93e6-9cd26ce322d6.yml, data/vt/executive/Phil-Scott-f3e613ff-3cd6-4b2c-b268-f6460d029f05.yml, data/vt/retired/Kate-Donnally-2f55322d-1014-4c90-82a6-728834df9ded.yml, settings.yml
Updating VT people data according to[ DATA-2446](https://civic-eagle.atlassian.net/browse/DATA-2446).
- retiring legislator
- updating `settings` to account for vacancy
=> VT: people data update

data/tx/legislature/Lulu-Flores-ab3ddc65-0fb9-476b-993f-b3dc4050127e.yml
File was looking a lil bare, added source & links
=> TX: Update Rep Flores

.pre-commit-config.yaml, data/ma/legislature/Aaron-L-Saunders-c3d23eba-caa6-4d2a-bbd2-5b8b2ca184ae.yml, data/ma/legislature/Adrianne-Pasateri-Ramos-300d40b3-9479-43c0-99d3-18f94e1110cc.yml, data/ma/legislature/Christopher-J-Worrell-59539448-5c3b-4d4d-8e96-48fabb01b10f.yml, data/ma/legislature/Christopher-Richard-Flanagan-c30f76b4-73d6-4795-be75-c46973d17f59.yml, data/ma/legislature/Estela-A-Reyes-824532f7-8dc9-4a1a-a7b3-16b2d0e78941.yml, data/ma/legislature/Francisco-E-Paulino-99109961-27e8-4e58-8269-3a1deb29f228.yml, data/ma/legislature/James-C-Arena-DeRosa-47ffc61b-0cae-4386-ae68-12b20eadd83f.yml, data/ma/legislature/Jennifer-Balinsky-Armini-eab9b69f-0434-4307-972c-6acce9deb370.yml, data/ma/legislature/Judith-A-Garcia-6f15f647-07f5-4739-a340-497798a474e7.yml, data/ma/legislature/Marcus-S-Vaughn-2dd65a68-0ea5-4c15-b5fe-bcde086eb357.yml, data/ma/legislature/Margaret-R-Scarsdale-a25fd374-e502-43bb-91fe-99c4b6c493a5.yml, data/ma/legislature/Pavel-M-Payano-1d33d1e7-dae9-4e98-aa9e-626b0d711d9a.yml, data/ma/legislature/Priscila-S-Sousa-a148ff77-2e73-4e42-a525-20e8d1ed569a.yml, data/ma/legislature/Rita-A-Mendes-87e3afd8-390c-45a3-97c6-2bb164ec1e90.yml, data/ma/legislature/Robyn-K-Kennedy-2fb1c0e0-edaa-4b55-9bbb-b6fe6b3e5dcc.yml, data/ma/legislature/Rodney-M-Elliott-49816a0c-b8e5-4586-859b-8a8f1ae9b6ab.yml, data/ma/legislature/Ryan-M-Hamilton-799d49f3-28e5-46a1-bcc8-6370e9fbf44a.yml, data/ma/legislature/Shirley-B-Arriaga-ff433cf6-2895-4e01-b143-26747500f8a4.yml
This is mainly just making sure each legislator has their given_name and family_name filled in, along with one missing email address. Source for the email is already included in the list of sources for the legislator.
Need this data to be updated for https://github.com/ProgressiveMass/legislator-scorecard/issues/101
=> Updating MA Legislator Info

settings.yml
To allow linting to pass on c[urrent PR](https://github.com/openstates/people/actions/runs/4736839696/jobs/8408895812?pr=1077)
=> WI: update vacancy date

data/ca/retired/Kevin-Faulconer-19544661-c24a-402a-aed6-ad9a1aaacc5a.yml
[No longer San Diego mayor](https://en.wikipedia.org/wiki/Kevin_Faulconer) as of December 10, 2020.
=> Update Kevin Faulconer

data/ca/municipalities/Matt-Mahan-bc1523dd-3485-408d-9918-27def331b652.yml
Matt Mahan was [sworn into office on January, 1 2023](https://www.mercurynews.com/2023/01/20/san-jose-mayor-matt-mahan-sets-date-for-inauguration-ceremony/)
=> Add Mayor of San Jose, Calif.

data/fl/executive/Ron-DeSantis-284392c5-5708-4014-9ea1-9552536c5a3e.yml
https://ballotpedia.org/Ron_DeSantis says his term ends in 2027.
Should resolve https://github.com/openstates/issues/issues/1073
=> fix rough end date for FL governor

data/co/committees/lower-Finance-b43f88fc-5e87-4387-8417-f55706b52da6.yml
Still had the old id on the committee, updated to new person id
=> MI: Update Person Id on Committee

data/fl/municipalities/Donna-Deegan-cfe1ad18-a6b1-4ea8-b800-a3d887d6431e.yml
[Took office on July 1, 2023](https://www.coj.net/office-of-mayor-donna-deegan).
=> Add Mayor Donna Deegan of Jacksonville

data/ma/legislature/Daniel-J-Ryan-c0519476-08fc-44af-9114-c77d197f883d.yml, data/ma/legislature/David-Biele-5fde161f-7456-4006-bffd-eaf6fedc5aa3.yml, data/ma/legislature/Francisco-E-Paulino-99109961-27e8-4e58-8269-3a1deb29f228.yml, data/ma/legislature/James-C-Arena-DeRosa-47ffc61b-0cae-4386-ae68-12b20eadd83f.yml, data/ma/legislature/John-Francis-Moran-15ff9d00-e05e-470a-b89c-36038b1dd5bb.yml, data/ma/legislature/Natalie-M-Blais-173c7e47-c770-4c5a-9794-4db19f9f5dce.yml, data/ma/legislature/Samantha-Montao-668db267-f9e1-4839-918d-c092741f96f9.yml, data/ma/legislature/Steven-C-Owens-f20dd448-92ef-458c-bf92-90e7e766072a.yml, data/ma/legislature/Susan-L-Moran-ade9765f-c80e-4127-adc4-cde294a455c6.yml, data/ma/legislature/William-F-MacGregor-9f0c5984-accf-45a3-8922-07aa7ade0030.yml, data/ma/retired/Edward-F-Coppinger-24929c64-96a3-41f9-b97f-dcf06024b8de.yml, data/ma/retired/Jon-Santiago-2b711986-660c-4eca-9072-31b2fda4542c.yml
Had 2 Reps retire, flagged in [Issue 1102](https://github.com/openstates/issues/issues/1102)
=> MA: update legislators

data/va/legislature/Eric-Phillips-704cecad-ef53-44e4-ad55-6c7a7e385e5c.yml, data/va/legislature/Tammy-Mulchi-c3391ffd-a783-4d34-81ca-ecad4cd6d16a.yml, data/va/retired/Frank-M-Ruff-Jr-7adbc89e-807a-476b-abb2-59f538389e2a.yml, data/va/retired/Les-R-Adams-5ab06b43-9b14-47fa-a67e-5e574cfd554e.yml
Had a shake up today in the legislature
=> VA: fix district 48 & 9

data/ri/legislature/Frank-S-Lombardi-e65ea2dc-d434-4c22-b156-346155e77f06.yml, data/ri/legislature/John-J-Lombardi-f9877000-1919-4f5b-a8b7-f05a1092bdab.yml
May not be matching legislators to bill sponsorships so trying this out.
=> RI: add short names to capture Lombardi

data/pa/municipalities/Cherelle-Parker-5aff4d4d-e7e2-4ac8-8ae0-8c03934fc62d.yml
Cherelle Parker became Philadelphia mayor [on January 2, 2024](https://www.phila.gov/departments/mayor/).
=> Philadelphia, Pa. Mayor

data/tx/municipalities/Jim-Ross-158a19b5-c7fa-4cc0-9201-1dea4cad40b9.yml
Jim Ross was [elected to the office of Mayor](https://www.arlingtontx.gov/city_hall/government/mayor/mayor_jim_ross) at the City of Arlington in June 2021
=> Arlington, Tex. Mayor

data/nc/municipalities/Vi-Lyles-ab069a58-7e8e-43f3-b5a7-9f49e041cd4c.yml
Vi Lyles is [still the Mayor](https://www.charlottenc.gov/City-Government/Leadership/Mayor) of Charlotte, N.C.
=> Charlotte Mayor

data/oh/municipalities/Shammas-Malik-1555be34-cc57-4d84-9b6e-b00e607f697d.yml
- Add Mayor of [Akron, Ohio](https://www.akronohio.gov/government/mayor_s_office/index.php)
=> Add Akron, Ohio Mayor

data/nv/municipalities.yml, data/nv/municipalities/Carolyn-G-Goodman-544a8b18-afc8-4c7c-bf3e-e70255cce5c6.yml, data/nv/municipalities/Michelle-Romero-45be3320-92ab-4d9d-b553-5c8efc6df887.yml, data/nv/municipalities/Pamela-A-Goynes-Brown-15c09249-ba32-47bb-ba43-c82d030ef78a.yml
- Update Las Vegas
- Update Henderson
- Add North Las Vegas
=> Add Las Vegas Metro Area Mayors

data/wi/municipalities/Cavalier-Johnson-fe397c40-e3ed-41a9-b43e-7a64b69b23f6.yml
Extend his term, he was re-elected
@NewAgeAirbender
=> Update MKE Mayor for re-election

data/us/legislature/Cindy-Hyde-Smith-3827ab20-4901-56bc-a6ea-e7c275da9eb9.yml, data/us/legislature/Eric-Schmitt-999df51b-9318-55b9-b0f6-d738ffc1d62d.yml, data/us/legislature/Greg-Lopez-b513aafd-8615-53db-910f-b0d3e4c0dec6.yml, data/us/legislature/JD-Vance-5a8792bc-1520-56aa-ab19-729008cd559b.yml, data/us/legislature/Joe-Manchin-III-3da2fb45-0c89-544c-b41d-888d623cf99c.yml, data/us/legislature/John-Fetterman-6f500f52-75ce-5cf0-afc6-5be71f0921d2.yml, data/us/legislature/John-Hoeven-18c027d3-52ca-5a48-a4d2-73167e382096.yml, data/us/legislature/Katie-Boyd-Britt-7bf077d8-e8b9-503e-b9c2-d18b55951e93.yml, data/us/legislature/Laphonza-R-Butler-0490575c-d32c-56f5-9d82-c0511ebe4fb8.yml, data/us/legislature/Mark-Kelly-30665d55-5695-5ede-930d-c92e63e4ee65.yml, data/us/legislature/Markwayne-Mullin-c1fcdb86-e58e-59ed-94f2-40e481824423.yml, data/us/legislature/Pete-Ricketts-e1b9405a-e695-5bc5-b3b0-6cdc1415f53c.yml, data/us/legislature/Peter-Welch-8addb5a8-a569-54b2-811b-b5d091350411.yml, data/us/legislature/Ted-Budd-67c3f0bb-7182-51b8-98d0-253144992bfe.yml, data/us/retired/Ken-Buck-ae816838-90af-512b-8a98-9389b05e9b6a.yml
Just need specific things from the automatic us update
=> US: Updates

data/us/committees/Border-Security-and-Enforcement-4465dcb9-cfb9-527d-89d0-d00d8257955f.yml, data/us/committees/Crime-Terrorism-and-Homeland-Security-52a7c8ec-803b-53e7-aea5-a66f1db69ac1.yml, data/us/committees/Crime-and-Federal-Government-Surveillance-52a7c8ec-803b-53e7-aea5-a66f1db69ac1.yml, data/us/committees/Cybersecurity-Infrastructure-Protection-and-Innovation-0cf615ba-ffad-58e4-be5a-0f58ab4932e2.yml, data/us/committees/Cybersecurity-and-Infrastructure-Protection-0cf615ba-ffad-58e4-be5a-0f58ab4932e2.yml, data/us/committees/Emergency-Preparedness-Response-and-Recovery-fb8de7cc-7ef1-582d-9adc-84d7da7cfac7.yml, data/us/committees/House-Committee-on-Homeland-Security-1b4c8042-794d-5f20-bfb9-114bf565df17.yml, data/us/committees/House-Committee-on-the-Budget-c9d6f979-7b13-5541-b8cd-58eab4eb60ed.yml, data/us/committees/House-Committee-on-the-Judiciary-87d1d54e-6852-588a-9f1c-4cf682d217bb.yml, data/us/committees/Immigration-Integrity-Security-and-Enforcement-af861711-e623-5952-ac02-b39cdac22a8b.yml, data/us/committees/Immigration-and-Citizenship-af861711-e623-5952-ac02-b39cdac22a8b.yml, data/us/committees/Intelligence-and-Counterterrorism-d2558c60-e895-5b2e-81b3-7f135dea7e33.yml, data/us/committees/The-Constitution-Civil-Rights-and-Civil-Liberties-a0e04954-0557-5917-bc5b-6b55b4510655.yml, data/us/committees/The-Constitution-and-Limited-Government-a0e04954-0557-5917-bc5b-6b55b4510655.yml
=> US: update committee memberships

data/az/executive/Katie-Hobbs-6e522a2a-e7b7-4713-a40f-c897e4341a87.yml, data/me/executive/Janet-Mills-3a068db0-d252-4bf9-929d-feb15cb84087.yml, data/nv/executive/Joe-Lombardo-d2c166cc-f53f-491d-9c4a-6c3fc68274fe.yml, data/or/executive/Tina-Kotek-c136922d-c34a-4b53-a56b-2201b139d469.yml, data/vt/executive/Phil-Scott-f3e613ff-3cd6-4b2c-b268-f6460d029f05.yml, data/wy/executive/Mark-Gordon-d832b435-0a83-49ba-abd8-6ce265eb52ef.yml
User submission but needed guide on formatting
=> Multi: add/update governors

data/va/legislature/Atoosa-Reaser-38f25fcb-2f54-411a-84d5-2d1f748d4183.yml
=> VA: add other_names to Rep Reaser

poetry.lock, pyproject.toml
=> Bump openstates to 6.20.8

data/ma/legislature/Amy-Sangiolo-adb7ebb2-480f-4215-859e-3a1194e9a598.yml, data/ma/legislature/Bridget-Plouffe-2b6d0884-6638-410e-87b7-243c7ca18a16.yml, data/ma/legislature/Dennis-Gallagher-3601344e-8a37-488b-a3b1-f355f4e52ea7.yml, data/ma/legislature/Dylan-Fernandes-cd05a88c-19f0-4fc5-bc3b-d339572842b7.yml, data/ma/legislature/Greg-Schwartz-2770216d-1802-435d-b147-4ca1d684dc45.yml, data/ma/legislature/Hadley-Luddy-8d481937-69c5-477d-ba72-e3b682ed0a4d.yml, data/ma/legislature/Homar-Gomez-6b27dd86-5c03-4223-957c-9efd12c70e04.yml, data/ma/legislature/John-Gaskey-013e94ee-496e-42f3-8b1b-f96c737f1f8e.yml, data/ma/legislature/Josh-Tarsky-9c847f4f-a48b-4d42-95cb-2b6a219f89ac.yml, data/ma/legislature/Justin-Thurber-4002361d-3211-4f02-b627-95d6e6a3f76c.yml, data/ma/legislature/Kelly-Dooner-062618e6-3ba4-4170-8b4f-9d0fa325a9ab.yml, data/ma/legislature/Ken-Sweezey-1eece00d-5b31-4be0-9263-b594863b295c.yml, data/ma/legislature/Leigh-Davis-386c6121-a2a4-4c92-b093-4abea066d840.yml, data/ma/legislature/Mark-Sylvia-7446bdd1-f6b4-40cb-a039-41f4be68833e.yml, data/ma/legislature/Michelle-Badger-a0c80d02-beb0-42c3-b7ff-31fc0d5351f5.yml, data/ma/legislature/Mike-Chaisson-0a74c581-eb5c-4935-b5c3-f4a77e6dcd31.yml, data/ma/legislature/Richard-Wells-e988f332-eba5-40a4-b55f-554728360e6c.yml, data/ma/legislature/Sean-Reid-d3ad855a-567f-443a-bb9f-480a0c95fb06.yml, data/ma/legislature/Steven-Ouellette-0fbe25ff-563e-4563-8523-f151bd839e3c.yml, data/ma/legislature/Tara-Hong-e5b9b2d0-1626-4151-93cf-73c16035a584.yml, data/ma/legislature/Thomas-Moakley-ebfdda03-c083-4a13-b3a4-f87f6e24adac.yml, data/ma/legislature/William-Driscoll-1b7d1710-da71-46cd-9ee3-fc891556f3a9.yml
...and also Bill Driscoll's email address.
=> Add more info for new MA legislators for 2025

data/us/legislature/Summer-L-Lee-e2bd9b69-7425-5f80-b432-41b690306379.yml
I noticed her photo wasn't working - looks like there's no photo for her in GPO - https://memberguide.gpo.gov/member-search/member/13232, but the office of the clerk seems to have a nice photo: https://clerk.house.gov/members/L000602
=> Update summer lee photo using clerk house office

data/me/legislature/Dani-OHalloran-49a5c100-0379-4ce8-af49-de4c4f817abc.yml, data/me/legislature/Marygrace-Cimino-ef0c0f85-eacc-4f97-9dba-d0781c40f274.yml, data/me/legislature/Michelle-Boyer-0b6557f4-ce52-460b-99af-ec88b847d81a.yml, data/me/legislature/Quentin-Chapman-d2a31aea-936e-459b-85e8-a031ba2756e9.yml, data/me/legislature/Sharon-Frost-05a89099-12b0-46b5-9f6e-002e1e621583.yml, data/me/legislature/Will-Tuell-76a9907f-f257-4621-b176-8e911bb8cf35.yml, data/mi/legislature/Joe-Pavlov-65bb5257-9a90-4b14-a7bd-aee9efd0ab55.yml, data/ms/legislature/Lataisha-Jackson-843ed177-0a3d-4f96-9df2-28ad7333c5a6.yml, data/nj/legislature/Melinda-Kane-a33ec105-c8ff-446b-ae8b-1a79f402f983.yml, data/nv/legislature/Angie-Taylor-d95b3a70-9bb4-43b8-a376-9d3151f9c44d.yml, data/nv/legislature/Carrie-A-Buck-189d270a-96e5-45af-a2b8-bbcc2ad225c1.yml, data/nv/legislature/Cinthia-Moore-0828d1f5-5772-4e62-88d8-1650abb8b749.yml, data/nv/legislature/Gregory-T-Hafen-II-33330e1e-b22d-49d7-bce8-6964b289683a.yml, data/nv/legislature/Rich-DeLong-204b492e-4b29-4e8e-9c3e-d2d0f0a8ceea.yml, data/nv/legislature/Shelly-Crawford-4acffaa7-5568-47e3-b476-bdf23867605e.yml, data/nv/legislature/Toby-Yurek-7b7e4737-3bd7-462f-894f-1397a87f04ab.yml, data/ny/legislature/Chris-Ryan-58b03f1c-af64-4079-8c24-e76dd0028166.yml, data/ny/legislature/Danny-Norber-2e502adc-4b0e-46fa-b5d4-0d2f7696db49.yml, data/ny/legislature/Emrita-Torres-4af19dc2-41c7-4b7e-b271-b23e20e1ccb1.yml, data/ny/legislature/Joe-Sempolinski-45837ecf-38a2-41cb-9de1-eae175a32dfe.yml, data/ny/legislature/Landon-Dais-4f486e74-0735-42fd-ab1c-9816a0ced550.yml, data/ny/legislature/Pat-Chludzinski-fe6635b5-8f6f-4bdb-ad2c-e68f53ed325b.yml, data/ny/legislature/Patrick-J-Carroll-04a87708-f68c-43ca-b892-fc987f4deb5a.yml, data/ny/legislature/Paul-Bologna-4a510afe-84a6-4b0c-ac8d-13bebadfff78.yml, data/ny/legislature/Robert-Carroll-a0a7d4b0-2624-4560-8129-dbca30c4d4a1.yml, data/ny/legislature/Steve-Chan-8a923d97-c689-4fb5-ac61-7b5e4ee950dd.yml, data/ny/legislature/Tommy-John-Schiavoni-60b6c2ff-a1ce-46a1-b484-affd805bc297.yml, data/sc/legislature/JD-Chaplin-a34e27e4-59ab-41a6-89ee-1b5d82fcbcf6.yml, data/sc/legislature/Jackie-Terribile-d5713eed-0ae5-4bf4-9dc8-7c3efdfae317.yml, data/sc/legislature/James-Teeple-4b8dd070-0114-4788-9d4c-21eab54496c0.yml
added other names - ME, MI, MS, NJ, NV, NY
=> Update multi jurisdiction other names 2 14

data/az/retired/Nancy-Barto-923989bc-5bbd-4b65-92ce-365d62b0e9f4.yml, data/az/retired/Raquel-Tern-61a50342-a072-402e-8592-29372cc93066.yml, data/nj/legislature/Angela-V-McKnight-d8c826c4-95c7-465b-8448-1f05495bfc45.yml, data/nj/legislature/Brian-Bergen-006c1bd9-54e9-49be-9d02-12dda1119149.yml, data/nj/legislature/Britnee-N-Timberlake-707e3027-d06f-4346-8c11-3ff1becbe725.yml, data/nj/legislature/Christian-E-Barranco-09c6e805-6356-4bcb-a7d3-6be479d41e9a.yml, data/nj/legislature/John-F-McKeon-1fec06e0-00df-4d84-8c9a-18e80a6f29e2.yml, data/nj/legislature/Parker-Space-1dde507a-70ed-4f89-95f8-cd11748a753c.yml, data/nj/legislature/Paul-D-Moriarty-f15f8b7e-96ee-41e8-b59c-b277927985c0.yml, data/nj/legislature/Raj-Mukherji-fe8bf5e4-85ed-423b-b2d8-301f29d3faea.yml, data/nj/retired/Fred-H-Madden-Jr-19da3948-96b1-4a6b-8734-a58fdcefc777.yml, data/pa/retired/Mike-Regan-ce0d90e3-b4dc-436f-a808-dc40946b6352.yml, data/tx/legislature/Mike-Schofield-df010291-7350-4262-9220-4c576730b2db.yml
Found and fixed some incorrect roles in AZ, NJ, PA, and TX
=> Fix issues with several roles in AZ, NJ, PA, and TX

data/us/legislature/Wesley-Bell-0555dc1b-b9eb-4d13-99aa-25b1c4349f83.yml
Fixes https://github.com/openstates/issues/issues/1323
=> Fix phone number for MO Rep Wesley Bell

data/ca/municipalities/Daniel-Lurie-2a268a23-e129-4791-9bec-5fd9278a3296.yml
- [Daniel Lurie sworn in](https://www.sfchronicle.com/sf/article/daniel-lurie-was-sworn-in-as-s-f-mayor-20013863.php) on January 8
=> Add Mayor of San Francisco

data/az/municipalities/Regina-Romero-8bda9792-de64-43d1-aa00-8844b2136f8b.yml
[Reelected](https://tucson.com/news/election/results/article_121f7306-78ba-11ee-835f-0336ecfef57c.html) on Nov 8, 2023.
=> Update Tucson mayor term end date

data/ma/legislature/Hannah-Bowen-f9a6f401-206b-43df-a1b9-0fc1cd8a3417.yml
Bowen was recently elected in a special election. This info all comes from the official state legislature site: https://malegislature.gov/Legislators/Profile/HLB1
=> Add more data for Hannah Bowen

data/ma/legislature/Lisa-Field-0a14e19e-3761-4aa2-887f-8b335d6e3eed.yml
Field was recently elected in a special election. This info all comes from the official state legislature site: https://malegislature.gov/Legislators/Profile/LMF1
=> Add more data for Lisa Field

data/wi/municipalities/Janesville-City-Council-6a6483f4-4abb-438e-a768-6adf264698bb.yml
- This technically isn't a Mayor, but it's here, and the information hasn't changed; updating the date so it can still be used by people.
=> Update Janesville Council
