scripts/manual_data.py

Manual Data load currently errors out if there is a retired legislator included. This allows manual load to with retired legislators.

Include retired legislators in manual data find

---

scripts/to_database.py

to_database spends a lot of time in `update_subobjects`. By making a fewer number of queries through testing in an exclusionary way for updates (if no objects are returned that differ vs. if all objects are the same), we should be able to improve performance.
Hopefully this will help with #55.

Attempt to improve performance of to_database

---

scripts/merge.py

load_yaml ensures that the order of keys won't change, since yaml.load doesn't otherwise use OrderedDicts. So that we don't have massive reorderings, change to use load_yaml everywhere.

Use load_yaml in merge.py

---

data/ut/people/Derek-Kitchen-8b1630fd-d86e-4c72-a6be-584d65bb8de0.yml

Reference: https://senate.utah.gov/senate-roster/
The link does not work with a capital 'P'.

Correct URL for UT House Representative Derek Kitchen.

---

data/al/organizations/Agriculture-and-Forestry-6cd9a311-5c34-4937-b3e5-420fff3bc342.yml
data/al/organizations/County-and-Municipal-Government-34b948fc-188f-49e1-82f0-ef4f597a759a.yml
data/al/organizations/Ethics-and-Campaign-Finance-7ebfafb8-73ce-46cf-b8ca-b8e37ea76461.yml
data/al/organizations/Health-8374da44-b0ce-48a1-9c91-d7b670b11bbf.yml
data/al/organizations/Mobile-County-Legislation-f6eb9877-616a-415d-8949-3304ea5ba7a7.yml
data/al/organizations/State-Government-4748fd62-1894-45b3-9317-b9b9c5d25b97.yml
data/al/organizations/Technology-and-Research-51cfd990-c01b-41cc-94da-368ac11f42dd.yml
data/al/organizations/Ways-and-Means-Education-010a25d3-70f8-401a-8338-00d4e137aa3a.yml
data/al/people/David-Sessions-fa2c59ea-1a07-429d-85e4-9c60652919aa.yml
data/al/people/Donnie-Chesteen-c1ce8b3f-ea56-4c8f-ab74-2a02b8d10063.yml
data/al/people/Jack-W-Williams-a7e333c5-03f2-4343-9981-956bcc1ea38e.yml
data/ca/organizations/Aging-and-Long-Term-Care-44b1b005-8336-412c-82d0-438df8dfd12a.yml
data/ca/organizations/Agriculture-7583a023-a98d-4244-9674-86f314c5f92a.yml
data/ca/organizations/Budget-28294af2-621f-4a09-8b24-acbfa48dd324.yml
data/ca/organizations/Economic-Development-and-Investment-in-Rural-California-e50036eb-c5a4-4c55-968f-f62f5196dbf0.yml
data/ca/organizations/Insurance-4da0a7ca-6c93-465a-90e1-73edd3dd48e7.yml
data/ca/organizations/Local-Government-2b44dba4-749c-409b-86d0-663c482dc5b0.yml
data/ca/organizations/Rail-af4ccbfc-956a-496b-967a-b39290621bba.yml
data/ca/organizations/Small-Business-and-Entrepreneurship-f5117af4-ffcf-49b4-8682-a27d199f956b.yml
data/ca/organizations/Wine-d2aeb66b-d9d1-48ba-9c54-aab0215252f4.yml
data/ca/people/Anna-M-Caballero-fe462917-df55-4a43-9fd8-970541544ca6.yml
data/mt/retired/Austin-Knudsen-6932f017-6867-409a-8321-6cf9dce312ef.yml

- Some of the updates removed past roles for legislators who had new roles.
- A random mistake occurred in the update of Austin Knudsen's record changing the district to something incorrect
I imagine that, if we want to keep past data (i.e. retired legislators), we probably also want to add end dates to previous roles. Ideally we probably have a script to mark a legislator as being done with a role, similar to the retiring one.

Fix data for past legislators

---

data/pr/people/Reinaldo-Vargas-Rodrguez-995de1a6-47d2-44f1-b6f9-a805c43f69b9.yml
data/pr/people/Wilson-Romn-Lpez-a8c74dd2-a9e8-44f3-9398-4b8b08f2f064.yml
data/vt/people/Harold-Colston-7fae5f96-31f0-4dba-af52-f14537de5263.yml
data/wa/people/Liz-Lovelett-f82a6162-120e-4bf2-90c4-02e22278d96e.yml

Some jurisidiction names ended up with capital letters, which doesn't match their official names. Fix these by changing the state names to lower case.

Fix jurisdiction names with capital letters

---

data/mn/organizations/E--Policy-Committee-71855a86-c986-4ab2-8a36-7e066fa45e62.yml
data/mn/organizations/Environment-and-Natural-Resources-Policy-and-Legacy-Finance-Committee-9340747d-32c2-4bae-b1d9-ef6e693fc394.yml
data/mn/organizations/Veterans-and-Military-Affairs-Finance-and-Policy-Committee-4b25eda8-48f5-4083-8712-e57c69305825.yml
data/mn/people/Carolyn-Laine-881a4eb7-f298-4b96-851b-77a6e6c1aae9.yml
data/mn/people/Jason-Rarick-f15c0d42-4380-4f9b-b66d-14ffe61e1a40.yml
data/mn/people/Karla-Bigham-8ef7f23a-5dde-476e-bde5-c5d64e5ddaff.yml
data/mn/people/Paul-E-Gazelka-0a0641bd-4b3a-4eb3-8044-b1ff468b8193.yml
data/mn/people/Steve-A-Cwodzinski-e67843ce-752d-4cc0-abb9-4a45b8b8fdca.yml
data/mn/people/Susan-Kent-232c625b-79bc-48d3-addb-cfffa0f15108.yml
data/mn/people/Warren-Limmer-dc676c57-0779-4d0e-9ba4-a07d7034dfa1.yml
settings.yml

Jason Rarick filled the vacancy for Senate district 11, so now his former House seat in district 11B is vacant. Also update some contact information and one name update (remove middle initial).

Updates to Minnesota legislators

---

data/ks/people/Stephanie-Clayton-6c410bc7-76fd-4488-aca4-5158a5a55d70.yml

There are two `roles` keys for this person. I'm not sure if this was the result of a manual error or if a scraper needs to be fixed.

Remove redundant `roles` key

---

data/fl/people/Dan-Daily-66308162-9b64-4d34-a8bc-fac71407f7d5.yml
data/fl/people/Jason-Shoaf-2bae38cc-f703-446b-93ec-576c0e388760.yml
data/fl/people/Randall-Scott-Maggard-2a415c08-da66-402b-ada6-93390a5df820.yml
settings.yml

Added missing FL legislators after the special election in 2019. Related to issue #185.

Fl legislators special election

---

scripts/to_database.py

When merging legislators in `to_database.py`, we currently only update `BillSponsorship` objects with the legislator's new ID. However, `PersonVote` objects should also be updated, as they would become disassociated with the legislator otherwise.

Update PersonVote IDs when merging legislators

---

data/wi/people/Tip-McGuire-c66ed13a-e5a7-49e0-9cce-02d677c5da15.yml
data/wi/retired/Peter-Barca-5e70f623-ae29-4013-ac58-b86c2616a9eb.yml

Peter Barca resigned last year, and Tip McGuire was elected to replace him.

WI: Replace Peter Barca with Tip McGuire

---

data/ma/municipalities/Michael-Cahill-c6fe5141-dd20-4e91-9a66-8db2452e6b81.yml

The OCD ID for Michael P. Cahill and Yvonne M. Spicer were identical. This gives Cahill a new OCD ID.

Add new ID for Michael Cahill

---

data/ar/legislature/Howard-M-Beaty-Jr-95d21faa-0431-4285-8cee-36fc918959b6.yml
data/ar/legislature/Jim-Hendren-9bfb23d9-4082-4c5c-89d7-dc670101ca2e.yml
data/ar/legislature/Stan-Berry-f738465d-9f00-4ea5-9e93-dbfeb4e8f47d.yml

Fixed voting aliases for two members and changed the party of Senator Jim Hendren who recently left the Republican party.
The last PR seems to have fixed the voting records of most members this session, save for these 5 members:
Senator Joyce Elliott
Rep. Howard M. Beaty, Jr.
Rep. Stan Berry
Rep. Karilyn Brown
Rep. Jamie Scott
Hoping this PR will fix the records for Beaty Jr. and Berry, but I'm not sure what would need to be done to fix the other 3 members as they seem to have the correct voting aliases.
Example voting events:
Senate:
https://openstates.org/vote/44220451-c352-40a3-be69-8d7ca3509057/
House:
https://openstates.org/vote/3a35b9b5-4176-42f9-b82a-b6444dd41bfb/

AR: Fix voting alias and party affiliation

---

scrape/ak.py

Matches format used in other states.

AK: add comma after city name in capitol_office.address

---

data/ak/committees/upper-Judiciary-06922c15-5f1a-4613-8228-4249351cb04d.yml

See https://github.com/openstates/issues/issues/598; there's a duplicate Senate Judiciary finance subcommittee now but this should work as a stopgap.

AK: Rename Senate Judiciary finance subcommittee

---

data/az/committees/lower-Criminal-Justice-Reform-ef90f103-d1ad-46b5-98ee-b0c9e040bea7.yml
data/az/committees/lower-Government--Elections-7c7b9aca-6a6d-4667-a300-583d7c23b359.yml
data/az/committees/lower-Natural-Resources-Energy--Water-87f8208e-5413-4157-b799-369ef85156e5.yml
data/az/committees/upper-Appropriations-2b268737-056c-4bfd-85aa-77e2755ef413.yml
data/az/committees/upper-Commerce-77d5471d-62b9-43ae-8025-45c7dc514efa.yml
data/az/committees/upper-Finance-5e1c21ea-30bc-4117-92b2-2f9d81a95756.yml
data/az/committees/upper-Health-and-Human-Services-0934ac59-938d-4edf-b6b2-15b3dc1c77e8.yml
data/az/committees/upper-Judiciary-759051cd-38fb-4bc0-9618-e3e3ba07ef01.yml
data/az/committees/upper-Natural-Resources-Energy-and-Water-0913184a-7fa5-42ca-834c-bba9b66eb6c6.yml
data/az/committees/upper-Senate-Ethics-9afa1568-b043-4315-9d2e-6eac1e845406.yml
data/ga/committees/lower-Appropriations-ffa1031f-825c-46d6-859d-0805910c0088.yml
data/ga/committees/lower-Code-Revision-3985938e-da58-4d36-b85c-420c6a602245.yml
data/ga/committees/lower-Creative-Arts--Entertainment-7688c988-561d-4de0-88c3-b9729a62b3db.yml
data/ga/committees/lower-Higher-Education-0a7df823-92b4-4b4b-a1af-b9371c3dfc98.yml
data/ga/committees/lower-Insurance-8d138bd7-8a77-4d1c-b1c5-3002a4e42fbb.yml
data/ga/committees/lower-Judiciary-9b0d5e83-9c34-4768-8d75-6ba42e57aa1f.yml
data/ga/committees/lower-Natural-Resources--Environment-dbbecd81-da59-4e17-9ccb-86a5b4cb683b.yml
data/ga/committees/lower-Rules-843530e9-fff7-4a21-a11c-f44d32faafad.yml
data/ga/committees/lower-Science-and-Technology-a9b9767c-9381-481d-b11e-319641f6f3ba.yml
data/ga/committees/lower-Ways--Means-de36f60f-5cd9-4e6c-aabc-55b9dbe2c95d.yml

Some people's OS IDs changed due to merging duplicate legislators. This needed to be fixed for their respective committees as well (or removed entirely if they retired).

Fix committee person IDs

---

data/ma/legislature/Brandy-Fluker-Oakley-99c9c9e7-f0e3-480b-ad38-de297e6c635a.yml

This makes it clear that Fluker is not her middle name, but part of her surname.

Add given and family names for Brandy Fluker Oakley

---

data/ny/executive/Kathy-Hochul-ccdd914d-9853-4fd2-9a80-ce6c962cdd18.yml
data/ny/retired/Andrew-Cuomo-72354c6b-937f-49eb-900f-2800210c14c6.yml

Andrew Cuomo [resigned on August 23, 2021](https://apnews.com/article/andrew-cuomo-resigns-17161f546bb83c32a337036ecf8d2a34); was replaced on the next day by [Gov. Kathy Hochul](https://www.governor.ny.gov).

Update N.Y. Governor

---

data/pa/committees/legislature-Applications-and-Information-Technology-c15c7ae9-33ac-49ed-afc4-7ce952c8209d.yml
data/pa/committees/legislature-Applications-and-Information-Technology-c79c70b8-56f0-455c-991f-b25ed162e767.yml
data/pa/committees/legislature-Capitol-Preservation-4d582918-e794-4bef-88e7-5855218adfc1.yml
data/pa/committees/legislature-Capitol-Preservation-cfbca86b-e9da-4a30-9dfa-06ce72f5bb4e.yml
data/pa/committees/legislature-Education-and-Outreach-099f14dd-dcaa-40d2-bc32-03e26ad68d49.yml
data/pa/committees/legislature-Education-and-Outreach-76007bee-6a7e-41b0-8797-2c7ebbcde8b9.yml
data/pa/committees/legislature-Executive-and-Administrative-7d87ec12-a972-46fb-804b-018c1b24104c.yml
data/pa/committees/legislature-Executive-and-Administrative-c88366af-fe55-453d-b084-cad0e4caa447.yml
data/pa/committees/legislature-Legislative-Audit-Advisory-Commission-00fe5896-1421-43ec-8daf-d2cf96c3a5bc.yml
data/pa/committees/legislature-Legislative-Audit-Advisory-Commission-86cd0018-81a3-4c78-8a53-b4b8b4f140c9.yml
data/pa/committees/legislature-Legislative-Budget-and-Finance-24032128-6e56-44d0-8ed1-c0d62e0b04ce.yml
data/pa/committees/legislature-Legislative-Budget-and-Finance-f5d762b9-fb9e-4406-acd9-b4e50d1e69b2.yml
data/pa/committees/legislature-Legislative-Reapportionment-Commission-8266f5d4-5bde-413b-ba4c-fd38c16eeeef.yml
data/pa/committees/legislature-Legislative-Reapportionment-Commission-f9dba631-2009-43cc-b94d-d4546a537ac8.yml
data/pa/committees/legislature-Local-Government-Commission-68a8947b-2c0c-4a8c-a2c7-c867f161f702.yml
data/pa/committees/legislature-Local-Government-Commission-ce0227c4-399d-4438-adcd-d8be230720c0.yml
data/pa/committees/legislature-Policy-7946261a-db12-4ee3-a08b-66e997132634.yml
data/pa/committees/legislature-Policy-c5cf445a-9a89-4b33-893b-d7618de6363e.yml
data/pa/committees/legislature-Research-and-Data-Analysis-5f5ac597-4b69-42b4-8c2d-49d560a6dfe3.yml
data/pa/committees/legislature-Research-and-Data-Analysis-ba5ee09f-9b85-4b58-96e4-c3398c76514f.yml
data/pa/committees/legislature-Sentencing-3638daed-4e52-4f6b-84ab-ebb94c1b6e6e.yml
data/pa/committees/legislature-Sentencing-475d6591-8e69-44bf-a429-f585a16a802c.yml
data/pa/committees/legislature-State-Government-Commission-16769289-34d5-4ee0-b27a-263dd9da9c5b.yml
data/pa/committees/legislature-State-Government-Commission-98fd59d7-2a29-4891-8d5d-60cfee592ba8.yml
data/pa/legislature/Kristin-Hill-cb724e4a-0e5e-4ebd-ac0c-f3dfda73aef6.yml
data/pa/legislature/Kyle-J-Mullins-625784c9-4cd0-417c-9c44-1acd53b34307.yml
data/pa/legislature/Rick-Krajewski-42ffbed1-2284-4018-a60f-b5bfa3f35833.yml
data/pa/legislature/Robert-Freeman-13bfe11c-06e2-4a1d-844d-d195ef18dc06.yml

Adds data for joint (`chamber="legislature"`) committees from Pennsylvania.
Note: Includes many public and non-legislative members on these committees and commissions.

PA comms: joint comms add

---

data/pa/committees/lower-Appropriations-e50fbc1f-5bbb-4fac-8e13-81944b24cab3.yml
data/pa/committees/lower-Insurance-1720a030-ad6f-4f43-bf17-d53c15bbbece.yml
data/pa/committees/lower-Liquor-Control-60fbf516-a187-4d9a-bcde-dea8ed90ce28.yml
data/pa/committees/lower-Transportation-71f8f6b1-77e9-44bb-a73a-7f868c8ad11c.yml
data/pa/legislature/Greg-Rothman-3e99b4f3-2efa-4330-b0b9-fb273b1322ea.yml
settings.yml

He has 2 ocd ids now, one for when he was a Representative & now senator. Adds his senatorial id to the `other_identifiers` & removes him from House committees that he's no longer a member of.

PA: update Sen Rothman & remove from lower committees

---

.yamllint

This should help with the random indentation that many of the scrapers produce.

don't require specific indentation for multi-line strings

---

data/il/municipalities/Brandon-Johnson-53d852f6-5c1f-47d4-861d-1505dae7f07c.yml

Brandon Johnson was [inaugurated today](https://abc7chicago.com/chicago-mayor-brandon-johnson-inauguration-livestream-credit-union-1-arena-mayoral-2023/13249293/#:~:text=Brandon%20Johnson%20sworn%20in%20as%20Chicago%20mayor%20at%20inauguration%20ceremony&text=CHICAGO%20(WLS)%20%2D%2D%20Brandon%20Johnson,were%20also%20officially%20sworn%20in.)

Add Chicago Mayor

---

data/co/legislature/Cleave-Simpson-715df6f2-cef6-4b88-b745-0207c8ffb4ff.yml
data/co/legislature/Janet-Buckner-a7d01880-beeb-4183-8dfa-a3300600c062.yml
data/co/legislature/Jim-Smallwood-e389192e-edc9-448f-a6ca-6a9eb800ae8e.yml
data/co/legislature/Rhonda-Fields-654b2a04-55a4-4158-b45f-2aefdef39a1c.yml
data/co/retired/Kerry-Donovan-e88f6ebc-1e9e-4c7c-9045-e6f3c22dc90a.yml

In CO several senators were redistricted into new districts. They weren't elected to the new district but are serving out the rest of their original term. In these cases having an explicit start date is helpful because we can't infer otherwise when they entered office based on the last election in the district.

Add start dates for CO senators redistricted into new districts

---

data/pa/committees/legislature-Applications-and-Information-Technology-f9931cb5-2756-4cf1-b638-0335244221a9.yml
data/pa/committees/legislature-Capitol-Preservation-f550ecf4-1f73-11ee-be56-0242ac120002.yml
data/pa/committees/legislature-Education-and-Outreach-a945c9cd-e707-444c-919e-7a22dddd2487.yml
data/pa/committees/legislature-Executive-and-Administrative-75f9b0f4-5992-4553-aa04-5590775c946f.yml
data/pa/committees/legislature-Legislative-Audit-Advisory-Commission-904c87ec-9e68-46c1-bdbd-722ec65d84ad.yml
data/pa/committees/legislature-Legislative-Budget-and-Finance-20ecb2f8-b10b-4af7-9864-99d47688d22d.yml
data/pa/committees/legislature-Legislative-Reapportionment-Commission-3d738fd4-609c-4128-ab65-8c060544cee1.yml
data/pa/committees/legislature-Local-Government-Commission-ce96beee-f0ef-481d-bf6e-e4d19834065e.yml
data/pa/committees/legislature-Policy-4463e25c-f094-4b2d-917d-8d0fca6ca315.yml
data/pa/committees/legislature-Research-and-Data-Analysis-bc5bcfc2-d3a1-45d7-9a5b-17a9a8b4fa38.yml
data/pa/committees/legislature-Sentencing-d497e31c-37fb-4fcb-bc88-2b7a89a84871.yml
data/pa/committees/legislature-State-Government-Commission-59063184-308e-4c68-8893-c31d19c97081.yml

Starting with fresh `ocd-organization` ids to hopefully calm this [duplicate key error](https://github.com/openstates/people/actions/runs/5511647200/jobs/10047472801) on the Update DB workflow

PA: refresh joint committees

---

data/de/executive/Anthony-Albence-1fbb3c2f-b3ec-421d-af2a-2f0af26b2939.yml

His term has an expiration date of 6/20/2023 but all indications are that he's still in office. Going to bump this to the end of the year and will amend if necessary.

Update Anthony Albence

---

data/ca/municipalities/London-Breed-d8e1c81d-a5a8-47f8-a1ea-126a2c63629f.yml
data/ut/municipalities/Erin-Mendenhall-cd98c525-5eff-4f47-a638-5ca88644e134.yml

- Erin Mendenhall was [sworn in for a second term](https://www.slc.gov/mayor/2024/01/03/salt-lake-city-mayor-erin-mendenhall-sworn-in-for-second-term/) on January 2, 2024.
- Following the passage of [Proposition H in 2022](https://ballotpedia.org/San_Francisco,_California,_Proposition_H,_Move_Local_Elections_to_Even-Numbered_Years_and_Change_Initiative_Petition_Signature_Requirements_Amendment_(November_2022)), mayoral elections in San Francisco were rescheduled to coincide with presidential elections. London Breed remains in office until 2025.

Repair Salt Lake City, San Francisco Mayors

---

data/fl/municipalities/Jane-Castor-56a74356-58b3-487e-a265-e950776bc249.yml

Jane Castor was [re-elected on March 7, 2023](https://ballotpedia.org/Jane_Castor#:~:text=Her%20current%20term%20ends%20on,elections%20in%20Tampa%20are%20nonpartisan.) and is not retired.

Tampa, Fla. Mayor

---

data/tx/municipalities/Jeff-Cheney-8f4cc828-656a-4037-82ab-9f1ed324c825.yml

Per [friscotexas.gov](https://www.friscotexas.gov/586/Jeff-Cheney), Jeff Cheney was reelected in November and will serve until 2026. So I updated his end_date to 12-31-2025, not seeing an exact date listed for his new term expiration.

Extend end_date of reelected Frisco, TX mayor

---

data/tx/municipalities/Eric-Johnson-9b26a8d9-1ccb-4c21-8b68-193aafb04c3f.yml

Eric Johnson was re-elected for another 4-year term as Dallas, TX mayor.
https://dallascityhall.com/government/citymayor/pages/default.aspx

Un-retire Eric Johnson, mayor of Dallas TX

---

data/oh/municipalities/Aftab-Pureval-aa81e0c6-dba7-4f08-b70e-a71c3f537200.yml

The mayor of Cincinnati, Ohio since 2022 is Aftab Pureval. For the end_date of his mayoral role, I've put the last day of 2025 as a best guess, because the next Cincinnati election will be held in November 2025.

Add new Cincinnati mayor

---

data/co/municipalities/Mike-Johnston-3b5c8213-a8a7-474b-903f-f5d67e75c4bc.yml

- Mike Johnston [assumed office on July 17, 2023](https://ballotpedia.org/Mayoral_election_in_Denver,_Colorado_(2023))

Add Denver Mayor

---

data/ma/legislature/John-Marsi-0e8c6c71-bca0-46fd-86d1-223d41ed5517.yml

Added email, Boston office phone number, and member code (the ID used by the MA legislature)

Add some fields to John Marsi

---

data/ma/legislature/John-J-Mahoney-2abbc0cb-6339-42d9-9947-69412a24301b.yml

It looks like the MA legislature website changed John Mahoney's member code from JJM1 to JJM2, and gave JJM1 to John Marsi who was elected earlier this year, breaking all of John Mahoney's existing links. Weird stuff! I checked on John Marsi's record and it looks fine, so this commit just cleans up Mahoney's.

Fix John Mahoney's bad data with old member code

---

data/pa/legislature/Dawn-W-Keefer-2a13f9df-b7e6-4281-82e4-f7263b6fa12e.yml
data/pa/legislature/Kristin-Hill-cb724e4a-0e5e-4ebd-ac0c-f3dfda73aef6.yml
data/pa/legislature/Mike-Jones-ce5d2c01-e29c-4eac-b06b-208d8c302dff.yml

These updates match data found on Ballotpedia/Wikipedia and add consistency to the PA legislator terms.
Also performed some validation of all the start/end dates I could after this fix – this data is visualized here:

Fix start/end dates for 3 legislators

---

data/mi/legislature/Carol-Glanville-86812673-e63a-4f36-aa3e-26de84380657.yml
data/mi/legislature/Tyrone-Carter-38d2f8c4-f40c-44b7-a2dd-57a4d5375572.yml
data/mi/retired/Abraham-Aiyash-5a87d637-4763-44a1-b763-a40c9a30b67e.yml
data/mi/retired/Andrew-Beeler-77456985-a7be-4384-9dfe-70373b8031f6.yml
data/mi/retired/Andrew-Fink-154e0e09-4da4-449d-9ebe-58c0b720e513.yml
data/mi/retired/Christine-Morse-4c46fce6-3e67-43a0-b396-5130a004c2a4.yml
data/mi/retired/Dale-Zorn-f87c906f-bf6e-41db-8ab6-cf736ba589d4.yml
data/mi/retired/Felicia-Brabec-ccfacab2-ec54-40f8-add5-2dfe02908055.yml
data/mi/retired/Graham-Filler-4eab6d53-e023-4314-934a-faffd35d78a2.yml
data/mi/retired/Jaime-Churches-8a444713-86ab-4a98-b26f-3f19302f0348.yml
data/mi/retired/Jenn-Hill-4f4e9d3d-0e2f-4c10-abcb-8308f0cb33e2.yml
data/mi/retired/Jim-Haadsma-7ac8386b-fa1e-4f5d-aaeb-e5614e771141.yml
data/mi/retired/Nate-Shannon-af52f259-fe60-4903-98b8-739a114a8deb.yml
data/mi/retired/Neil-Friske-79ed6347-2370-40bc-9570-996894d0b600.yml
data/mi/retired/Rachel-Hood-85cde8af-86e7-4d74-9bf7-2cc79ccfab39.yml
data/mi/retired/Robert-Bezotte-f5b2c77c-88b8-4ea7-854a-789b660e5a91.yml
data/mi/retired/Terence-Mekoski-9f06fa9b-d9ea-4424-9e2a-3e2e02e979fb.yml

17 MIchigan legislators have missing or incorrect tenure dates. This PR fixes them and ensures none of them overlap.

Make MI start/end dates consistent

---

data/tx/legislature/Borris-L-Miles-3475b324-1c9b-4513-90e6-063aba5ac04e.yml
data/tx/legislature/Bryan-Hughes-8326538c-c907-43b2-a6db-76434036afd7.yml
data/tx/legislature/Carol-Alvarado-e78373de-6d96-44db-b552-6da34ed992fc.yml
data/tx/legislature/Claudia-Ordaz-Perez-6feda596-fd20-429b-ae4e-bedab7e5a1c5.yml
data/tx/legislature/Csar-Blanco-3e0f0e51-20c0-4da4-82b5-ff81606148d0.yml
data/tx/legislature/Gary-Gates-5ff88048-ebd8-4ac3-af9c-d02e1305ef37.yml
data/tx/legislature/James-Talarico-5e4e2fd2-e8a9-46f3-aab5-ffbc782afa8b.yml
data/tx/legislature/Mayes-Middleton-1399b6ba-cbfa-45ca-bf91-6ba89fe777bf.yml
data/tx/legislature/Phil-King-98bef50a-73c7-4139-9b8e-628d0e89d659.yml
data/tx/legislature/Richard-Pea-Raymond-d4a94a68-02a7-44c0-901f-9cd57350229a.yml
data/tx/legislature/Roland-Gutierrez-68767ec3-151c-413f-aeb8-f35dd6c5f35c.yml
data/tx/legislature/Ryan-Guillen-f0ede995-2253-4f7b-a922-6da34e4de194.yml
data/tx/legislature/Tan-Parker-fa4817bf-6dc6-4deb-9965-cf3f208ec976.yml
data/tx/legislature/Trent-Ashby-68f05872-16c8-4d3a-ab5f-ea667ca52b27.yml
data/tx/retired/Charles-Doc-Anderson-a289901c-76aa-4288-a4b9-3bb1bf081c89.yml
data/tx/retired/Drew-Springer-f1332c39-f120-4ccd-ac64-cae40b2be91a.yml
data/tx/retired/Jacey-Jetton-8c82ede2-a4c6-4625-92ca-2b24c370de17.yml
data/tx/retired/Shawn-Thierry-26b8304b-24ea-411d-8d85-e348ba6951c7.yml

18 Texas legislators have incorrect or duplicate tenure dates. This PR fixes them and ensures none of them overlap.

Make TX legislature start/end dates consistent

---

data/ma/legislature/Brandy-Fluker-Oakley-99c9c9e7-f0e3-480b-ad38-de297e6c635a.yml

https://www.dotnews.com/2025/wedding-bells-peal-12th-suffolk-state-rep
>She was Brandy Fluker-Oakley when she was elected as a representative for parts of Dorchester and Mattapan in the Legislature. On New Year’s Eve, she married her partner, Omar Reid, a real estate developer from Dorchester, and she is now Brandy Fluker-Reid.

Update Brandy Fluker Oakley to Brandy Fluker-Reid due to marriage name change

---

data/ca/municipalities/Todd-Gloria-1465de6a-ec39-4986-b3e4-e30ef7a47c20.yml

Reelected for his final term in 2024: https://www.cbs8.com/article/news/politics/elections/san-diego-mayor-live-election-results-todd-gloria-larry-turner/509-e91ee437-2d97-4050-b52e-67df1c47d21d
December 10th seems to be the more accurate end date for SD mayoral terms.

Update San Diego mayor term end date

---

data/ia/retired/Molly-Buck-1ca8e33b-4983-4e18-ab06-414f8b119916.yml

Sorry my last change didn't sync before you merged - found one more instance - this time it was `https:// https://` (with a space in between)

double-protocol issue in links (sorry - one more!)
